In [291]:
import requests
from datetime import datetime
import json

# An api key is emailed to you when you sign up to a plan
# Get a free API key at https://api.the-odds-api.com/
API_KEY = 'aebd96cf4102e7110abbfad4f9a5e3a0'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# First get a list of in-season sports
#   The sport 'key' from the response can be used to get odds in the next request
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
SPORT = 'basketball_nba'
sports_response = requests.get(
    f'https://api.the-odds-api.com/v4/sports/{SPORT}/events', 
    params={
        'api_key': API_KEY
    }
)


if sports_response.status_code != 200:
    print(f'Failed to get sports: status_code {sports_response.status_code}, response body {sports_response.text}')

else:
    print('List of in season sports:', sports_response.json())
    sports_data = sports_response.json()
    pretty_data = json.dumps(sports_data, indent=4)
    print(pretty_data)

# Extracting the event IDs into a list
event_ids_list = [event['id'] for event in sports_data]

List of in season sports: [{'id': '3bc5054ad4bc0f2c50cd87a3fcb8cd45', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-24T23:05:00Z', 'home_team': 'Detroit Pistons', 'away_team': 'New York Knicks'}, {'id': 'f39fff52133794a10c16ba61d2c0eeda', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-25T01:35:00Z', 'home_team': 'Memphis Grizzlies', 'away_team': 'Oklahoma City Thunder'}, {'id': '19aca5a6e1fa8b1aa68505d3f1d75b37', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-25T02:05:00Z', 'home_team': 'Los Angeles Clippers', 'away_team': 'Denver Nuggets'}, {'id': '5a935d4f284b3fcf84515f522e9079f9', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-25T23:05:00Z', 'home_team': 'Orlando Magic', 'away_team': 'Boston Celtics'}, {'id': '8af134619ff871a0b76992d76de7e224', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-26T00:05:00Z', 'home_team': 'Milwaukee Bucks', 'away_team': 'Indiana Pacers'}, {'id': 'cce8a5bd08230e0c507ec925508889bc', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-26T01:30:00Z', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Los Angeles Lakers'}, {'id': '5ed30106dccf7db288641b620e248242', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-26T17:05:00Z', 'home_team': 'Miami Heat', 'away_team': 'Cleveland Cavaliers'}, {'id': '64727ecb83898fd5fa4ba086945dd594', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2025-04-27T00:30:00Z', 'home_team': 'Golden State Warriors', 'away_team': 'Houston Rockets'}]
[
    {
        "id": "3bc5054ad4bc0f2c50cd87a3fcb8cd45",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-24T23:05:00Z",
        "home_team": "Detroit Pistons",
        "away_team": "New York Knicks"
    },
    {
        "id": "f39fff52133794a10c16ba61d2c0eeda",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-25T01:35:00Z",
        "home_team": "Memphis Grizzlies",
        "away_team": "Oklahoma City Thunder"
    },
    {
        "id": "19aca5a6e1fa8b1aa68505d3f1d75b37",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-25T02:05:00Z",
        "home_team": "Los Angeles Clippers",
        "away_team": "Denver Nuggets"
    },
    {
        "id": "5a935d4f284b3fcf84515f522e9079f9",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-25T23:05:00Z",
        "home_team": "Orlando Magic",
        "away_team": "Boston Celtics"
    },
    {
        "id": "8af134619ff871a0b76992d76de7e224",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-26T00:05:00Z",
        "home_team": "Milwaukee Bucks",
        "away_team": "Indiana Pacers"
    },
    {
        "id": "cce8a5bd08230e0c507ec925508889bc",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-26T01:30:00Z",
        "home_team": "Minnesota Timberwolves",
        "away_team": "Los Angeles Lakers"
    },
    {
        "id": "5ed30106dccf7db288641b620e248242",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-26T17:05:00Z",
        "home_team": "Miami Heat",
        "away_team": "Cleveland Cavaliers"
    },
    {
        "id": "64727ecb83898fd5fa4ba086945dd594",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-27T00:30:00Z",
        "home_team": "Golden State Warriors",
        "away_team": "Houston Rockets"
    }
]

In [292]:



def get_game_odds(event_ids, API_KEY=API_KEY, sport='basketball_nba', regions='us', markets='player_points', odds_format='decimal', date_format='iso', time_from='2025-02-10T00:00:00Z', time_to='2025-05-10T00:00:00Z'):
    # Convert input times to ISO format
    iso_time_from = datetime.strptime(time_from, "%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%dT%H:%M:%SZ")
    iso_time_to = datetime.strptime(time_to, "%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%dT%H:%M:%SZ")
    
    # Initialize a list to store data for all events
    all_games_data = []

    for event_id in event_ids:
        # Make the request to get odds data for the event
        odds_response = requests.get(
            f'https://api.the-odds-api.com/v4/sports/{sport}/events/{event_id}/odds',
            params={
                'api_key': API_KEY,
                'regions': regions,
                'markets': markets,
                'oddsFormat': odds_format,
                'dateFormat': date_format,
                'commenceTimeFrom': iso_time_from,
                'commenceTimeTo': iso_time_to
            }
        )

        if odds_response.status_code != 200:
            print(f'Failed to get odds for EventID {event_id}: status_code {odds_response.status_code}, response body {odds_response.text}')
        else:
            odds_json = odds_response.json()
            print(f'Number of events for EventID {event_id}:', len(odds_json))
            all_games_data.append(odds_json)
            
            # Save the response to a file for each event
            with open(f"games_data_{event_id}.json", "w") as file:
                json.dump(odds_json, file)

            # Check the usage quota
            print(f'Remaining requests for EventID {event_id}:', odds_response.headers['x-requests-remaining'])
            print(f'Used requests for EventID {event_id}:', odds_response.headers['x-requests-used'])

    return all_games_data

event_ids = event_ids_list

games_data = get_game_odds(event_ids)
with open("games_data.json", "w") as file:
    json.dump(games_data, file)

Number of events for EventID 3bc5054ad4bc0f2c50cd87a3fcb8cd45: 7
Remaining requests for EventID 3bc5054ad4bc0f2c50cd87a3fcb8cd45: 217
Used requests for EventID 3bc5054ad4bc0f2c50cd87a3fcb8cd45: 283
Number of events for EventID f39fff52133794a10c16ba61d2c0eeda: 7
Remaining requests for EventID f39fff52133794a10c16ba61d2c0eeda: 216
Used requests for EventID f39fff52133794a10c16ba61d2c0eeda: 284
Number of events for EventID 19aca5a6e1fa8b1aa68505d3f1d75b37: 7
Remaining requests for EventID 19aca5a6e1fa8b1aa68505d3f1d75b37: 215
Used requests for EventID 19aca5a6e1fa8b1aa68505d3f1d75b37: 285
Number of events for EventID 5a935d4f284b3fcf84515f522e9079f9: 7
Remaining requests for EventID 5a935d4f284b3fcf84515f522e9079f9: 214
Used requests for EventID 5a935d4f284b3fcf84515f522e9079f9: 286
Number of events for EventID 8af134619ff871a0b76992d76de7e224: 7
Remaining requests for EventID 8af134619ff871a0b76992d76de7e224: 213
Used requests for EventID 8af134619ff871a0b76992d76de7e224: 287
Number of events for EventID cce8a5bd08230e0c507ec925508889bc: 7
Remaining requests for EventID cce8a5bd08230e0c507ec925508889bc: 212
Used requests for EventID cce8a5bd08230e0c507ec925508889bc: 288
Number of events for EventID 5ed30106dccf7db288641b620e248242: 7
Remaining requests for EventID 5ed30106dccf7db288641b620e248242: 211
Used requests for EventID 5ed30106dccf7db288641b620e248242: 289
Number of events for EventID 64727ecb83898fd5fa4ba086945dd594: 7
Remaining requests for EventID 64727ecb83898fd5fa4ba086945dd594: 210
Used requests for EventID 64727ecb83898fd5fa4ba086945dd594: 290

In [293]:
import pandas as pd
pd.set_option('display.max_columns', None)

with open('games_data.json', 'r') as file:
    data = json.load(file)

#print(data)
pretty_data = json.dumps(data, indent=4)
print(pretty_data)

[
    {
        "id": "3bc5054ad4bc0f2c50cd87a3fcb8cd45",
        "sport_key": "basketball_nba",
        "sport_title": "NBA",
        "commence_time": "2025-04-24T23:05:00Z",
        "home_team": "Detroit Pistons",
        "away_team": "New York Knicks",
        "bookmakers": [
            {
                "key": "draftkings",
                "title": "DraftKings",
                "markets": [
                    {
                        "key": "player_points",
                        "last_update": "2025-04-24T16:17:28Z",
                        "outcomes": [
                            {
                                "name": "Over",
                                "description": "Jalen Brunson",
                                "price": 1.87,
                                "point": 28.5
                            },
                            {
                                "name": "Under",
                                "description": "Jalen Brunson",
                                "price": 1.87,
                                "point": 28.5
                            },
                            {
                                "name": "Over",
                                "description": "Cade Cunningham",
                                "price": 1.91,
                                "point": 28.5
                            },
                            {
                                "name": "Under",
                                "description": "Cade Cunningham",
                                "price": 1.83,
                                "point": 28.5
                            },
                            {
                                "name": "Over",
                                "description": "Karl-Anthony Towns",
                                "price": 1.95,
                                "point": 22.5
                            },
                            {
                                "name": "Under",
                                "description": "Karl-Anthony Towns",
                                "price": 1.8,
                                "point": 22.5
                            },
                            {
                                "name": "Over",
                                "description": "OG Anunoby",
                                "price": 1.91,
                                "point": 16.5
                            },
                            {
                                "name": "Under",
                                "description": "OG Anunoby",
                                "price": 1.83,
                                "point": 16.5
                            },
                            {
                                "name": "Over",
                                "description": "Mikal Bridges",
                                "price": 1.8,
                                "point": 15.5
                            },
                            {
                                "name": "Under",
                                "description": "Mikal Bridges",
                                "price": 1.95,
                                "point": 15.5
                            },
                            {
                                "name": "Over",
                                "description": "Malik Beasley",
                                "price": 1.87,
                                "point": 14.5
                            },
                            {
                                "name": "Under",
                                "description": "Malik Beasley",
                                "price": 1.87,
                                "point": 14.5
                            },
                            {
                                "name": "Over",
                                "description": "Tobias Harris",
                                "price": 1.91,
                                "point": 14.5
                            },
                            {
                                "name": "Under",
                                "description": "Tobias Harris",
                                "price": 1.83,
                                "point": 14.5
                            },
                            {
                                "name": "Over",
                                "description": "Jalen Duren",
                                "price": 1.87,
                                "point": 11.5
                            },
                            {
                                "name": "Under",
                                "description": "Jalen Duren",
                                "price": 1.87,
                                "point": 11.5
                            },
                            {
                                "name": "Over",
                                "description": "Josh Hart",
                                "price": 1.87,
                                "point": 11.5
                            },
                            {
                                "name": "Under",
                                "description": "Josh Hart",
                                "price": 1.87,
                                "point": 11.5
                            },
                            {
                                "name": "Over",
                                "description": "Dennis Schroder",
                                "price": 1.91,
                                "point": 10.5
                            },
                            {
                                "name": "Under",
                                "description": "Dennis Schroder",
                                "price": 1.83,
                                "point": 10.5
                            },
                            {
                                "name": "Over",
                                "description": "Ausar Thompson",
                                "price": 1.83,
                                "point": 9.5
                            },
                            {
                                "name": "Under",
                                "description": "Ausar Thompson",
                                "price": 1.91,
                                "point": 9.5
                            },
                            {
                                "name": "Over",
                                "description": "Tim Hardaway Jr",
                                "price": 1.91,
                                "point": 9.5
                            },
                            {
                                "name": "Under",
                                "description": "Tim Hardaway Jr",
                                "price": 1.83,
                                "point": 9.5
                            },
                            {
                                "name": "Over",
                                "description": "Mitchell Robinson",
                                "price": 1.87,
                                "point": 3.5
                            },
                            {
                                "name": "Under",
                                "description": "Mitchell Robinson",
                                "price": 1.87,
                                "point": 3.5
                            }
                        ]
                    }
                ]
            },
            {
                "key": "fanduel",
                "title": "FanDuel",
                "markets": [
                    {
                        "key": "player_points",
                        "last_update": "2025-04-24T16:17:21Z",
                        "outcomes": [
                            {
                                "name": "Over",
                                "description": "Josh Hart",
                                "price": 1.85,
                                "point": 11.5
                            },
                            {
                                "name": "Under",
                                "description": "Josh Hart",
                                "price": 1.89,
                                "point": 11.5
                            },
                            {
                                "name": "Over",
                                "description": "Cade Cunningham",
                                "price": 1.91,
                                "point": 28.5
                            },
                            {
                                "name": "Under",
                                "description": "Cade Cunningham",
                                "price": 1.83,
                                "point": 28.5
                            },
                            {
                                "name": "Over",
                                "description": "Malik Beasley",
                                "price": 1.89,
                                "point": 14.5
                            },
                            {
                                "name": "Under",
                                "description": "Malik Beasley",
                                "price": 1.85,
                                "point": 14.5
                            },
                            {
                                "name": "Over",
                                "description": "Mikal Bridges",
                                "price": 1.77,
                                "point": 15.5
                            },
                            {
                                "name": "Under",
                                "description": "Mikal Bridges",
                                "price": 1.98,
                                "point": 15.5
                            },
                            {
                                "name": "Over",
                                "description": "Ausar Thompson",
                                "price": 1.83,
                                "point": 9.5
                            },
                            {
                                "name": "Under",
                                "description": "Ausar Thompson",
                                "price": 1.91,
                                "point": 9.5
                            },
                            {
                                "name": "Over",
                                "description": "OG Anunoby",
                                "price": 1.94,
                                "point": 16.5
                            },
                            {
                                "name": "Under",
                                "description": "OG Anunoby",
                                "price": 1.8,
                                "point": 16.5
                            },
                            {
                                "name": "Over",
                                "description": "Jalen Brunson",
                                "price": 1.93,
                                "point": 28.5
                            },
                            {
                                "name": "Under",
                                "description": "Jalen Brunson",
                                "price": 1.82,
                                "point": 28.5
                            },
                            {
                                "name": "Over",
                                "description": "Jalen Duren",
                                "price": 1.91,
                                "point": 11.5
                            },
                            {
                                "name": "Under",
                                "description": "Jalen Duren",
                                "price": 1.83,
                                "point": 11.5
                            },
                            {
                                "name": "Over",
                                "description": "Karl-Anthony Towns",
                                "price": 1.89,
                                "point": 22.5
                            },
                            {
                                "name": "Under",
                                "description": "Karl-Anthony Towns",
                                "price": 1.85,
                                "point": 22.5
                            },
                            {
                                "name": "Over",
                                "description": "Tim Hardaway Jr",
                                "price": 1.98,
                                "point": 9.5
                            },
                            {
                                "name": "Under",
                                "description": "Tim Hardaway Jr",
                                "price": 1.78,
                                "point": 9.5
                            },
                            {
                                "name": "Over",
                                "description": "Dennis Schroder",
                                "price": 1.98,
                                "point": 10.5
                            },
                            {
                                "name": "Under",
                                "description": "Dennis Schroder",
                                "price": 1.77,
                                "point": 10.5
                            },
                            {
                                "name": "Over",
                                "description": "Tobias Harris",
                                "price": 1.94,
                                "point": 14.5
                            },
                            {
                                "name": "Under",
                                "description": "Tobias Harris",
                                "price": 1.8,
                                "point": 14.5
                            }
                        ]
                    }
                ]
            },
            {
                "key": "betmgm",
                "title": "BetMGM",
                "markets": [
                    {
                        "key": "player_points",
                        "last_update": "2025-04-24T16:17:16Z",
                        "outcomes": [
                            {
                                "name": "Over",
                                "description": "OG Anunoby",
                                "price": 1.91,
                                "point": 16.5
                            },
                            {
                                "name": "Under",
                                "description": "OG Anunoby",
                                "price": 1.83,
                                "point": 16.5
                            },
                            {
                                "name": "Over",
                                "description": "Jalen Duren",
                                "price": 1.87,
                                "point": 11.5
                            },
                            {
                                "name": "Under",
                                "description": "Jalen Duren",
                                "price": 1.85,
                                "point": 11.5
                            },
                            {
                                "name": "Over",
                                "description": "Cade Cunningham",
                                "price": 1.91,
                                "point": 28.5
                            },
                            {
                                "name": "Under",
                                "description": "Cade Cunningham",
                                "price": 1.83,
                                "point": 28.5
                            },
                            {
                                "name": "Over",
                                "description": "Tim Hardaway Jr",
                                "price": 1.91,
                                "point": 9.5
                            },
                            {
                                "name": "Under",
                                "description": "Tim Hardaway Jr",
                                "price": 1.83,
                                "point": 9.5
                            },
                            {
                                "name": "Over",
                                "description": "Josh Hart",
                                "price": 1.85,
                                "point": 11.5
                            },
                            {
                                "name": "Under",
                                "description": "Josh Hart",
                                "price": 1.91,
                                "point": 11.5
                            },
                            {
                                "name": "Over",
                                "description": "Karl-Anthony Towns",
                                "price": 1.69,
                                "point": 21.5
                            },
                            {
                                "name": "Under",
                                "description": "Karl-Anthony Towns",
                                "price": 2.1,
                                "point": 21.5
                            },
                            {
                                "name": "Over",
                                "description": "Tobias Harris",
                                "price": 1.91,
                                "point": 14.5
                            },
                            {
                                "name": "Under",
                                "description": "Tobias Harris",
                                "price": 1.83,
                                "point": 14.5
                            },
                            {
                                "name": "Over",
                                "description": "Mitchell Robinson",
                                "price": 1.74,
                                "point": 3.5
                            },
                            {
                                "name": "Under",
                                "description": "Mitchell Robinson",
                                "price": 2.0,
                                "point": 3.5
                            },
                            {
                                "name": "Over",
                                "description": "Malik Beasley",
                                "price": 1.83,
                                "point": 14.5
                            },
                            {
                                "name": "Under",
                                "description": "Malik Beasley",
                                "price": 1.91,
                                "point": 14.5
                            },
                            {
                                "name": "Over",
                                "description": "Dennis Schroder",
                                "price": 1.91,
                                "point": 10.5
                            },
                            {
                                "name": "Under",
                                "description": "Dennis Schroder",
                                "price": 1.8,
                                "point": 10.5
                            },
                            {

In [294]:
from datetime import datetime
import pytz
def extract_data(data):
    extracted_data = []
    utc_zone = pytz.timezone('UTC')
    eastern_zone = pytz.timezone('US/Eastern')

    # Loop through each entry in the JSON
    for data in data:
        match_id = data['id']
        home_team = data['home_team']
        away_team = data['away_team']
        for bookmaker in data['bookmakers']:
            bookmaker_title = bookmaker['title']
            print(bookmaker_title)
            for market in bookmaker['markets']:
                market_title = market['key']
                print(market_title)
                for outcome in market['outcomes']:
                    OverOrUnder = outcome['name']
                    player_name = outcome['description']
                    outcome_price = outcome['price']
                    points = outcome['point']
                    #outcome_datetime = datetime.fromtimestamp(outcome['timestamp'], utc_zone).astimezone(eastern_zone)
                    #outcome_datetime = outcome_datetime.strftime('%Y-%m-%d %H:%M:%S')
                    extracted_data.append({
                        'ID': match_id,
                        #'StartDate': outcome_datetime,  
                        'HomeTeam': home_team,
                        'AwayTeam': away_team,
                        'Bookmaker': bookmaker_title,
                        'Market': market_title,
                        'Player': player_name,
                        'Outcome': OverOrUnder,
                        'Points': points,
                        'Price': outcome_price,
                    })
    df = pd.DataFrame(extracted_data)
    df
    return df

df = extract_data(data)
df

DraftKings
player_points
FanDuel
player_points
BetMGM
player_points
BetOnline.ag
player_points
Bovada
player_points
BetRivers
player_points
DraftKings
player_points
FanDuel
player_points
BetOnline.ag
player_points
BetMGM
player_points
BetRivers
player_points
Bovada
player_points
DraftKings
player_points
FanDuel
player_points
BetMGM
player_points
BetOnline.ag
player_points
BetRivers
player_points
Bovada
player_points
DraftKings
player_points
FanDuel
player_points
BetMGM
player_points
BetOnline.ag
player_points
Bovada
player_points
DraftKings
player_points
BetOnline.ag
player_points
BetMGM
player_points
FanDuel
player_points
Bovada
player_points
BetRivers
player_points
FanDuel
player_points
DraftKings
player_points
BetRivers
player_points
BetOnline.ag
player_points
BetMGM
player_points
Bovada
player_points
DraftKings
player_points
FanDuel
player_points
BetOnline.ag
player_points
BetMGM
player_points
Bovada
player_points
BetMGM
player_points
Bovada
player_points

,ID,HomeTeam,AwayTeam,Bookmaker,Market,Player,Outcome,Points,Price
0,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Jalen Brunson,Over,28.5,1.87
1,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Jalen Brunson,Under,28.5,1.87
2,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Cade Cunningham,Over,28.5,1.91
3,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Cade Cunningham,Under,28.5,1.83
4,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Karl-Anthony Towns,Over,22.5,1.95
...,...,...,...,...,...,...,...,...,...
1113,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Fred VanVleet,Under,12.5,1.91
1114,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Jalen Green,Over,20.5,1.95
1115,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Jalen Green,Under,20.5,1.80
1116,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Tari Eason,Over,8.5,1.95
1117,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Tari Eason,Under,8.5,1.80

In [295]:
df['adjusted_price'] = ((df['Price'] * 1) - 1)

In [296]:
def decimal_to_us_odds(decimal_odds):
    if decimal_odds == 1.00:
        return 0  # No payout, return 0 or another meaningful value
    elif decimal_odds >= 2:
        # Underdogs: (decimal_odds - 1) * 100
        return (decimal_odds - 1) * 100
    else:
        # Favorites: -100 / (decimal_odds - 1)
        return -100 / (decimal_odds - 1)

In [297]:
df['US_Odds'] = df['Price'].apply(decimal_to_us_odds)
df

,ID,HomeTeam,AwayTeam,Bookmaker,Market,Player,Outcome,Points,Price,adjusted_price,US_Odds
0,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Jalen Brunson,Over,28.5,1.87,0.87,-114.942529
1,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Jalen Brunson,Under,28.5,1.87,0.87,-114.942529
2,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Cade Cunningham,Over,28.5,1.91,0.91,-109.890110
3,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Cade Cunningham,Under,28.5,1.83,0.83,-120.481928
4,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Karl-Anthony Towns,Over,22.5,1.95,0.95,-105.263158
...,...,...,...,...,...,...,...,...,...,...,...
1113,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Fred VanVleet,Under,12.5,1.91,0.91,-109.890110
1114,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Jalen Green,Over,20.5,1.95,0.95,-105.263158
1115,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Jalen Green,Under,20.5,1.80,0.80,-125.000000
1116,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Tari Eason,Over,8.5,1.95,0.95,-105.263158
1117,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Tari Eason,Under,8.5,1.80,0.80,-125.000000

In [298]:
df.to_excel('player_points_data.xlsx', index=False)

In [299]:
#Limit the sportsbooks to only my avaliable sportsbooks. 
accepted_sportsbooks = ['FanDuel', 'DraftKings', 'BetMGM', 'Caesars','BetRivers']

accceptedsportsbooksdf = df[df['Bookmaker'].isin(accepted_sportsbooks)]
df

,ID,HomeTeam,AwayTeam,Bookmaker,Market,Player,Outcome,Points,Price,adjusted_price,US_Odds
0,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Jalen Brunson,Over,28.5,1.87,0.87,-114.942529
1,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Jalen Brunson,Under,28.5,1.87,0.87,-114.942529
2,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Cade Cunningham,Over,28.5,1.91,0.91,-109.890110
3,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Cade Cunningham,Under,28.5,1.83,0.83,-120.481928
4,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Karl-Anthony Towns,Over,22.5,1.95,0.95,-105.263158
...,...,...,...,...,...,...,...,...,...,...,...
1113,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Fred VanVleet,Under,12.5,1.91,0.91,-109.890110
1114,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Jalen Green,Over,20.5,1.95,0.95,-105.263158
1115,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Jalen Green,Under,20.5,1.80,0.80,-125.000000
1116,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Tari Eason,Over,8.5,1.95,0.95,-105.263158
1117,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,Bovada,player_points,Tari Eason,Under,8.5,1.80,0.80,-125.000000

In [300]:
# First, drop duplicates on the key columns
unique_combinations = accceptedsportsbooksdf[['Player', 'Outcome', 'Points']].drop_duplicates()

# Split into Over and Under
overs = unique_combinations[unique_combinations['Outcome'] == 'Over']
unders = unique_combinations[unique_combinations['Outcome'] == 'Under']

# Convert to list of tuples (or dicts, if you prefer)
over_list = list(overs.itertuples(index=False, name=None))
under_list = list(unders.itertuples(index=False, name=None))

print(over_list)
overs

[('Jalen Brunson', 'Over', 28.5), ('Cade Cunningham', 'Over', 28.5), ('Karl-Anthony Towns', 'Over', 22.5), ('OG Anunoby', 'Over', 16.5), ('Mikal Bridges', 'Over', 15.5), ('Malik Beasley', 'Over', 14.5), ('Tobias Harris', 'Over', 14.5), ('Jalen Duren', 'Over', 11.5), ('Josh Hart', 'Over', 11.5), ('Dennis Schroder', 'Over', 10.5), ('Ausar Thompson', 'Over', 9.5), ('Tim Hardaway Jr', 'Over', 9.5), ('Mitchell Robinson', 'Over', 3.5), ('Karl-Anthony Towns', 'Over', 21.5), ('Jalen Brunson', 'Over', 29.5), ('Isaiah Stewart II', 'Over', 4.5), ('Miles McBride', 'Over', 4.5), ('Cade Cunningham', 'Over', 26.5), ('Ausar Thompson', 'Over', 10.5), ('Malik Beasley', 'Over', 15.5), ('Mikal Bridges', 'Over', 16.5), ('Dennis Schroder', 'Over', 9.5), ('Jalen Duren', 'Over', 12.5), ('Cade Cunningham', 'Over', 27.5), ('Josh Hart', 'Over', 12.5), ('OG Anunoby', 'Over', 15.5), ('OG Anunoby', 'Over', 17.5), ('Mikal Bridges', 'Over', 17.5), ('Tobias Harris', 'Over', 13.5), ('Malik Beasley', 'Over', 16.5), ('Jalen Brunson', 'Over', 27.5), ('Dennis Schroder', 'Over', 11.5), ('Tobias Harris', 'Over', 15.5), ('Tim Hardaway Jr', 'Over', 8.5), ('Karl-Anthony Towns', 'Over', 23.5), ('Ausar Thompson', 'Over', 8.5), ('Jalen Brunson', 'Over', 26.5), ('Karl-Anthony Towns', 'Over', 20.5), ('Cade Cunningham', 'Over', 29.5), ('Malik Beasley', 'Over', 13.5), ('Jalen Duren', 'Over', 10.5), ('Mitchell Robinson', 'Over', 2.5), ('Shai Gilgeous-Alexander', 'Over', 31.5), ('Ja Morant', 'Over', 24.5), ('Jalen Williams', 'Over', 21.5), ('Desmond Bane', 'Over', 20.5), ('Jaren Jackson Jr', 'Over', 19.5), ('Chet Holmgren', 'Over', 15.5), ('Scotty Pippen Jr', 'Over', 10.5), ('Santi Aldama', 'Over', 10.5), ('Isaiah Hartenstein', 'Over', 9.5), ('Luguentz Dort', 'Over', 9.5), ('Zach Edey', 'Over', 8.5), ('Alex Caruso', 'Over', 6.5), ('Cason Wallace', 'Over', 6.5), ('Jaren Jackson Jr', 'Over', 18.5), ('Ja Morant', 'Over', 23.5), ('Chet Holmgren', 'Over', 16.5), ('Desmond Bane', 'Over', 19.5), ('Zach Edey', 'Over', 7.5), ('Luke Kennard', 'Over', 4.5), ('Scotty Pippen Jr', 'Over', 11.5), ('Isaiah Joe', 'Over', 6.5), ('Aaron Wiggins', 'Over', 7.5), ('Shai Gilgeous-Alexander', 'Over', 32.5), ('Santi Aldama', 'Over', 9.5), ('Isaiah Hartenstein', 'Over', 10.5), ('Shai Gilgeous-Alexander', 'Over', 30.5), ('Ja Morant', 'Over', 25.5), ('Desmond Bane', 'Over', 21.5), ('Ja Morant', 'Over', 22.5), ('Desmond Bane', 'Over', 18.5), ('Jalen Williams', 'Over', 20.5), ('Alex Caruso', 'Over', 7.5), ('Jaren Jackson Jr', 'Over', 17.5), ('Chet Holmgren', 'Over', 17.5), ('Shai Gilgeous-Alexander', 'Over', 29.5), ('Cason Wallace', 'Over', 5.5), ('Luguentz Dort', 'Over', 8.5), ('Jalen Williams', 'Over', 22.5), ('Luguentz Dort', 'Over', 10.5), ('Jalen Williams', 'Over', 19.5), ('Jaren Jackson Jr', 'Over', 20.5), ('Nikola Jokic', 'Over', 26.5), ('Kawhi Leonard', 'Over', 25.5), ('James Harden', 'Over', 22.5), ('Jamal Murray', 'Over', 20.5), ('Ivica Zubac', 'Over', 16.5), ('Norman Powell', 'Over', 16.5), ('Aaron Gordon', 'Over', 15.5), ('Michael Porter Jr', 'Over', 12.5), ('Christian Braun', 'Over', 11.5), ('Russell Westbrook', 'Over', 11.5), ('Derrick Jones', 'Over', 6.5), ('Kris Dunn', 'Over', 6.5), ('Ivica Zubac', 'Over', 17.5), ('Aaron Gordon', 'Over', 14.5), ('James Harden', 'Over', 23.5), ('Bogdan Bogdanovic', 'Over', 5.5), ('Nikola Jokic', 'Over', 27.5), ('Kawhi Leonard', 'Over', 24.5), ('Nikola Jokic', 'Over', 25.5), ('Michael Porter Jr', 'Over', 13.5), ('Kawhi Leonard', 'Over', 23.5), ('Norman Powell', 'Over', 18.5), ('Christian Braun', 'Over', 10.5), ('Michael Porter Jr', 'Over', 11.5), ('Russell Westbrook', 'Over', 10.5), ('Jamal Murray', 'Over', 19.5), ('Kawhi Leonard', 'Over', 26.5), ('Russell Westbrook', 'Over', 12.5), ('Norman Powell', 'Over', 17.5), ('James Harden', 'Over', 21.5), ('Christian Braun', 'Over', 12.5), ('James Harden', 'Over', 24.5), ('Ivica Zubac', 'Over', 18.5), ('Norman Powell', 'Over', 15.5), ('Jamal Murray', 'Over', 21.5), ('Nikola Jokic', 'Over', 24.5), ('Kris Dunn', 'Over', 5.5), ('Derrick Jones', 'Over', 7.5), ('Aaron Gordon', 'Over', 16.5), ('Paolo Banchero', 'Over', 27.5), ('Franz Wagner', 'Over', 24.5), ('Jayson Tatum', 'Over', 23.5), ('Jaylen Brown', 'Over', 19.5), ('Kristaps Porzingis', 'Over', 17.5), ('Derrick White', 'Over', 15.5), ('Jrue Holiday', 'Over', 9.5), ('Wendell Carter Jr', 'Over', 9.5), ('Kentavious Caldwell-Pope', 'Over', 7.5), ('Kentavious Caldwell-Pope', 'Over', 6.5), ('Jayson Tatum', 'Over', 24.5), ('Cory Joseph', 'Over', 4.5), ('Derrick White', 'Over', 14.5), ('Jaylen Brown', 'Over', 20.5), ('Kristaps Porzingis', 'Over', 18.5), ('Paolo Banchero', 'Over', 28.5), ('Giannis Antetokounmpo', 'Over', 32.5), ('Damian Lillard', 'Over', 22.5), ('Pascal Siakam', 'Over', 19.5), ('Tyrese Haliburton', 'Over', 19.5), ('Myles Turner', 'Over', 15.5), ('Bobby Portis', 'Over', 13.5), ('Bennedict Mathurin', 'Over', 11.5), ('Aaron Nesmith', 'Over', 10.5), ('Andrew Nembhard', 'Over', 10.5), ('Kyle Kuzma', 'Over', 10.5), ('Brook Lopez', 'Over', 8.5), ('Obi Toppin', 'Over', 7.5), ('Bennedict Mathurin', 'Over', 12.5), ('Bobby Portis', 'Over', 12.5), ('Aaron Nesmith', 'Over', 11.5), ('Kevin Porter Jr.', 'Over', 7.5), ('Taurean Prince', 'Over', 5.5), ('Tyrese Haliburton', 'Over', 18.5), ('T.J. McConnell', 'Over', 6.5), ('Gary Trent Jr', 'Over', 8.5), ('Damian Lillard', 'Over', 21.5), ('LeBron James', 'Over', 23.5), ('Austin Reaves', 'Over', 18.5), ('Luka Doncic', 'Over', 30.5), ('Rudy Gobert', 'Over', 9.5), ('Julius Randle', 'Over', 18.5), ('Rui Hachimura', 'Over', 11.5), ('Anthony Edwards', 'Over', 26.5), ('Mike Conley', 'Over', 6.5), ('Jaden McDaniels', 'Over', 12.5), ('LeBron James', 'Over', 22.5), ('Rui Hachimura', 'Over', 10.5), ('Austin Reaves', 'Over', 17.5), ('Jaden McDaniels', 'Over', 11.5), ('Anthony Edwards', 'Over', 25.5), ('Naz Reid', 'Over', 11.5), ('Nickeil Alexander-Walker', 'Over', 6.5), ('Donte DiVincenzo', 'Over', 9.5), ('Dorian Finney-Smith', 'Over', 6.5), ('Julius Randle', 'Over', 17.5), ('Tyler Herro', 'Over', 26.5), ('Donovan Mitchell', 'Over', 25.5), ('Bam Adebayo', 'Over', 19.5), ('Darius Garland', 'Over', 18.5), ('Evan Mobley', 'Over', 17.5), ('Andrew Wiggins', 'Over', 16.5), ('Jarrett Allen', 'Over', 11.5), ('Davion Mitchell', 'Over', 10.5), ('Tyler Herro', 'Over', 25.5), ('Andrew Wiggins', 'Over', 15.5), ('Evan Mobley', 'Over', 16.5), ('Max Strus', 'Over', 7.5), ("Kel'el Ware", 'Over', 6.5), ('Duncan Robinson', 'Over', 5.5), ('Jarrett Allen', 'Over', 10.5), ('Ty Jerome', 'Over', 10.5), ('Donovan Mitchell', 'Over', 24.5), ("De'Andre Hunter", 'Over', 9.5), ('Brandin Podziemski', 'Over', 12.5), ('Draymond Green', 'Over', 8.5), ('Jimmy Butler', 'Over', 21.5), ('Stephen Curry', 'Over', 26.5), ('Alperen Sengun', 'Over', 19.5), ('Fred VanVleet', 'Over', 12.5), ('Moses Moody', 'Over', 9.5), ('Amen Thompson', 'Over', 12.5), ('Tari Eason', 'Over', 8.5), ('Steven Adams', 'Over', 3.5), ('Dillon Brooks', 'Over', 11.5), ('Jalen Green', 'Over', 20.5), ('Jabari Smith Jr', 'Over', 7.5)]

                  Player Outcome  Points
0          Jalen Brunson    Over    28.5
2        Cade Cunningham    Over    28.5
4     Karl-Anthony Towns    Over    22.5
6             OG Anunoby    Over    16.5
8          Mikal Bridges    Over    15.5
...                  ...     ...     ...
1096          Tari Eason    Over     8.5
1098        Steven Adams    Over     3.5
1100       Dillon Brooks    Over    11.5
1102         Jalen Green    Over    20.5
1104     Jabari Smith Jr    Over     7.5

[209 rows x 3 columns]

In [301]:
#For a specified team in the list find the highest US Odds
def find_highest_us_odds_for_player_Over(df, Player, Points):
    # Filter the dataframe for the specified team
    player_df = df[(df['Player'] == Player) & (df['Outcome'] == 'Over') & (df['Points'] == Points)]
    if not player_df.empty:
        return player_df.loc[[player_df['US_Odds'].idxmax()]]
    else:
        return None

find_highest_us_odds_for_player_Over(accceptedsportsbooksdf, 'Darius Garland', 19.5)

#For a specified team in the list find the highest US Odds
def find_highest_us_odds_for_player_Under(df, Player, Points):
    # Filter the dataframe for the specified team
    player_df = df[(df['Player'] == Player) & (df['Outcome'] == 'Under') & (df['Points'] == Points)]
    if not player_df.empty:
        return player_df.loc[[player_df['US_Odds'].idxmax()]]
    else:
        return None

find_highest_us_odds_for_player_Under(accceptedsportsbooksdf, 'Darius Garland', 19.5)

In [302]:
results = []  # Use a list instead of a DataFrame

# Loop through all Over combinations
for line in over_list:
    player, outcome, points = line
    maxvaluedf = find_highest_us_odds_for_player_Over(accceptedsportsbooksdf, player, points)
    results.append(maxvaluedf)

# Combine into a single DataFrame
final_df_over = pd.concat(results, ignore_index=True)

# View the result
print(type(final_df_over))  # <class 'pandas.core.frame.DataFrame'>
final_df_over

<class 'pandas.core.frame.DataFrame'>

,ID,HomeTeam,AwayTeam,Bookmaker,Market,Player,Outcome,Points,Price,adjusted_price,US_Odds
0,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,FanDuel,player_points,Jalen Brunson,Over,28.5,1.93,0.93,-107.526882
1,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,BetRivers,player_points,Cade Cunningham,Over,28.5,1.93,0.93,-107.526882
2,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,BetRivers,player_points,Karl-Anthony Towns,Over,22.5,1.97,0.97,-103.092784
3,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,FanDuel,player_points,OG Anunoby,Over,16.5,1.94,0.94,-106.382979
4,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Mikal Bridges,Over,15.5,1.80,0.80,-125.000000
...,...,...,...,...,...,...,...,...,...,...,...
204,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Tari Eason,Over,8.5,1.95,0.95,-105.263158
205,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Steven Adams,Over,3.5,1.74,0.74,-135.135135
206,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Dillon Brooks,Over,11.5,1.87,0.87,-114.942529
207,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Jalen Green,Over,20.5,1.95,0.95,-105.263158
208,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Jabari Smith Jr,Over,7.5,1.74,0.74,-135.135135

In [303]:
results = []  # Use a list instead of a DataFrame

# Loop through all Over combinations
for line in under_list:
    player, outcome, points = line
    maxvaluedf = find_highest_us_odds_for_player_Under(accceptedsportsbooksdf, player, points)
    results.append(maxvaluedf)

# Combine into a single DataFrame
final_df_under = pd.concat(results, ignore_index=True)

# View the result
print(type(final_df_under))  # <class 'pandas.core.frame.DataFrame'>
final_df_under

<class 'pandas.core.frame.DataFrame'>

,ID,HomeTeam,AwayTeam,Bookmaker,Market,Player,Outcome,Points,Price,adjusted_price,US_Odds
0,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Jalen Brunson,Under,28.5,1.87,0.87,-114.942529
1,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,DraftKings,player_points,Cade Cunningham,Under,28.5,1.83,0.83,-120.481928
2,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,FanDuel,player_points,Karl-Anthony Towns,Under,22.5,1.85,0.85,-117.647059
3,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,BetRivers,player_points,OG Anunoby,Under,16.5,1.88,0.88,-113.636364
4,3bc5054ad4bc0f2c50cd87a3fcb8cd45,Detroit Pistons,New York Knicks,BetRivers,player_points,Mikal Bridges,Under,15.5,2.08,1.08,108.000000
...,...,...,...,...,...,...,...,...,...,...,...
204,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Tari Eason,Under,8.5,1.80,0.80,-125.000000
205,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Steven Adams,Under,3.5,2.00,1.00,100.000000
206,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Dillon Brooks,Under,11.5,1.87,0.87,-114.942529
207,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Jalen Green,Under,20.5,1.80,0.80,-125.000000
208,64727ecb83898fd5fa4ba086945dd594,Golden State Warriors,Houston Rockets,BetMGM,player_points,Jabari Smith Jr,Under,7.5,2.00,1.00,100.000000

In [304]:
final_df_under.to_excel('player_points_results.xlsx', index=False)

In [305]:
merged_df = pd.merge(final_df_over, final_df_under, on=['Player', 'Points'], how='inner')

In [306]:
merged_df.to_excel('player_points_results.xlsx', index=False)