In [2022]:
import requests
from datetime import datetime
import json

# An api key is emailed to you when you sign up to a plan
# Get a free API key at https://api.the-odds-api.com/
API_KEY = 'aebd96cf4102e7110abbfad4f9a5e3a0'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# First get a list of in-season sports
#   The sport 'key' from the response can be used to get odds in the next request
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
sports_response = requests.get(
    'https://api.the-odds-api.com/v4/sports', 
    params={
        'api_key': API_KEY
    }
)


if sports_response.status_code != 200:
    print(f'Failed to get sports: status_code {sports_response.status_code}, response body {sports_response.text}')

else:
    print('List of in season sports:', sports_response.json())
    sports_data = sports_response.json()
    pretty_data = json.dumps(sports_data, indent=4)
    print(pretty_data)

List of in season sports: [{'key': 'americanfootball_ncaaf', 'group': 'American Football', 'title': 'NCAAF', 'description': 'US College Football', 'active': True, 'has_outrights': False}, {'key': 'americanfootball_ncaaf_championship_winner', 'group': 'American Football', 'title': 'NCAAF Championship Winner', 'description': 'US College Football Championship Winner', 'active': True, 'has_outrights': True}, {'key': 'americanfootball_nfl_super_bowl_winner', 'group': 'American Football', 'title': 'NFL Super Bowl Winner', 'description': 'Super Bowl Winner 2025/2026', 'active': True, 'has_outrights': True}, {'key': 'americanfootball_ufl', 'group': 'American Football', 'title': 'UFL', 'description': 'United Football League', 'active': True, 'has_outrights': False}, {'key': 'aussierules_afl', 'group': 'Aussie Rules', 'title': 'AFL', 'description': 'Aussie Football', 'active': True, 'has_outrights': False}, {'key': 'baseball_kbo', 'group': 'Baseball', 'title': 'KBO', 'description': 'KBO League', 'active': True, 'has_outrights': False}, {'key': 'baseball_milb', 'group': 'Baseball', 'title': 'MiLB', 'description': 'Minor League Baseball', 'active': True, 'has_outrights': False}, {'key': 'baseball_mlb', 'group': 'Baseball', 'title': 'MLB', 'description': 'Major League Baseball', 'active': True, 'has_outrights': False}, {'key': 'baseball_mlb_world_series_winner', 'group': 'Baseball', 'title': 'MLB World Series Winner', 'description': 'World Series Winner 2025', 'active': True, 'has_outrights': True}, {'key': 'baseball_npb', 'group': 'Baseball', 'title': 'NPB', 'description': 'Nippon Professional Baseball', 'active': True, 'has_outrights': False}, {'key': 'basketball_euroleague', 'group': 'Basketball', 'title': 'Basketball Euroleague', 'description': 'Basketball Euroleague', 'active': True, 'has_outrights': False}, {'key': 'basketball_nba', 'group': 'Basketball', 'title': 'NBA', 'description': 'US Basketball', 'active': True, 'has_outrights': False}, {'key': 'basketball_nba_championship_winner', 'group': 'Basketball', 'title': 'NBA Championship Winner', 'description': 'Championship Winner 2024/2025', 'active': True, 'has_outrights': True}, {'key': 'boxing_boxing', 'group': 'Boxing', 'title': 'Boxing', 'description': 'Boxing Bouts', 'active': True, 'has_outrights': False}, {'key': 'cricket_international_t20', 'group': 'Cricket', 'title': 'International Twenty20', 'description': 'International Twenty20', 'active': True, 'has_outrights': False}, {'key': 'cricket_ipl', 'group': 'Cricket', 'title': 'IPL', 'description': 'Indian Premier League', 'active': True, 'has_outrights': False}, {'key': 'cricket_psl', 'group': 'Cricket', 'title': 'Pakistan Super League', 'description': 'Pakistan Super League', 'active': True, 'has_outrights': False}, {'key': 'cricket_test_match', 'group': 'Cricket', 'title': 'Test Matches', 'description': 'International Test Matches', 'active': True, 'has_outrights': False}, {'key': 'golf_pga_championship_winner', 'group': 'Golf', 'title': 'PGA Championship Winner', 'description': '2025 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_the_open_championship_winner', 'group': 'Golf', 'title': 'The Open Winner', 'description': '2025 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_us_open_winner', 'group': 'Golf', 'title': 'US Open Winner', 'description': '2025 Winner', 'active': True, 'has_outrights': True}, {'key': 'icehockey_ahl', 'group': 'Ice Hockey', 'title': 'AHL', 'description': 'American Hockey League', 'active': True, 'has_outrights': False}, {'key': 'icehockey_liiga', 'group': 'Ice Hockey', 'title': 'Liiga', 'description': 'Finnish SM League', 'active': True, 'has_outrights': False}, {'key': 'icehockey_nhl', 'group': 'Ice Hockey', 'title': 'NHL', 'description': 'US Ice Hockey', 'active': True, 'has_outrights': False}, {'key': 'icehockey_nhl_championship_winner', 'group': 'Ice Hockey', 'title': 'NHL Championship Winner', 'description': 'Stanley Cup Winner 2024/2025', 'active': True, 'has_outrights': True}, {'key': 'icehockey_sweden_allsvenskan', 'group': 'Ice Hockey', 'title': 'HockeyAllsvenskan', 'description': 'Swedish Hockey Allsvenskan', 'active': True, 'has_outrights': False}, {'key': 'icehockey_sweden_hockey_league', 'group': 'Ice Hockey', 'title': 'SHL', 'description': 'Swedish Hockey League', 'active': True, 'has_outrights': False}, {'key': 'lacrosse_ncaa', 'group': 'Lacrosse', 'title': 'NCAA Lacrosse', 'description': 'College Lacrosse', 'active': True, 'has_outrights': False}, {'key': 'mma_mixed_martial_arts', 'group': 'Mixed Martial Arts', 'title': 'MMA', 'description': 'Mixed Martial Arts', 'active': True, 'has_outrights': False}, {'key': 'politics_us_presidential_election_winner', 'group': 'Politics', 'title': 'US Presidential Elections Winner', 'description': '2028 US Presidential Election Winner', 'active': True, 'has_outrights': True}, {'key': 'rugbyleague_nrl', 'group': 'Rugby League', 'title': 'NRL', 'description': 'Aussie Rugby League', 'active': True, 'has_outrights': False}, {'key': 'soccer_argentina_primera_division', 'group': 'Soccer', 'title': 'Primera División - Argentina', 'description': 'Argentine Primera División', 'active': True, 'has_outrights': False}, {'key': 'soccer_australia_aleague', 'group': 'Soccer', 'title': 'A-League', 'description': 'Aussie Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_austria_bundesliga', 'group': 'Soccer', 'title': 'Austrian Football Bundesliga', 'description': 'Austrian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_belgium_first_div', 'group': 'Soccer', 'title': 'Belgium First Div', 'description': 'Belgian First Division A', 'active': True, 'has_outrights': False}, {'key': 'soccer_brazil_campeonato', 'group': 'Soccer', 'title': 'Brazil Série A', 'description': 'Brasileirão Série A', 'active': True, 'has_outrights': False}, {'key': 'soccer_brazil_serie_b', 'group': 'Soccer', 'title': 'Brazil Série B', 'description': 'Campeonato Brasileiro Série B', 'active': True, 'has_outrights': False}, {'key': 'soccer_chile_campeonato', 'group': 'Soccer', 'title': 'Primera División - Chile', 'description': 'Campeonato Chileno', 'active': True, 'has_outrights': False}, {'key': 'soccer_china_superleague', 'group': 'Soccer', 'title': 'Super League - China', 'description': 'Chinese Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_conmebol_copa_libertadores', 'group': 'Soccer', 'title': 'Copa Libertadores', 'description': 'CONMEBOL Copa Libertadores', 'active': True, 'has_outrights': False}, {'key': 'soccer_conmebol_copa_sudamericana', 'group': 'Soccer', 'title': 'Copa Sudamericana', 'description': 'CONMEBOL Copa Sudamericana', 'active': True, 'has_outrights': False}, {'key': 'soccer_denmark_superliga', 'group': 'Soccer', 'title': 'Denmark Superliga', 'description': 'Danish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_efl_champ', 'group': 'Soccer', 'title': 'Championship', 'description': 'EFL Championship', 'active': True, 'has_outrights': False}, {'key': 'soccer_england_league1', 'group': 'Soccer', 'title': 'League 1', 'description': 'EFL League 1', 'active': True, 'has_outrights': False}, {'key': 'soccer_england_league2', 'group': 'Soccer', 'title': 'League 2', 'description': 'EFL League 2 ', 'active': True, 'has_outrights': False}, {'key': 'soccer_epl', 'group': 'Soccer', 'title': 'EPL', 'description': 'English Premier League', 'active': True, 'has_outrights': False}, {'key': 'soccer_fa_cup', 'group': 'Soccer', 'title': 'FA Cup', 'description': 'Football Association Challenge Cup', 'active': True, 'has_outrights': False}, {'key': 'soccer_fifa_world_cup_winner', 'group': 'Soccer', 'title': 'FIFA World Cup Winner', 'description': 'FIFA World Cup Winner 2026', 'active': True, 'has_outrights': True}, {'key': 'soccer_finland_veikkausliiga', 'group': 'Soccer', 'title': 'Veikkausliiga - Finland', 'description': 'Finnish  Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_france_ligue_one', 'group': 'Soccer', 'title': 'Ligue 1 - France', 'description': 'French Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_france_ligue_two', 'group': 'Soccer', 'title': 'Ligue 2 - France', 'description': 'French Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_germany_bundesliga', 'group': 'Soccer', 'title': 'Bundesliga - Germany', 'description': 'German Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_germany_bundesliga2', 'group': 'Soccer', 'title': 'Bundesliga 2 - Germany', 'description': 'German Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_germany_liga3', 'group': 'Soccer', 'title': '3. Liga - Germany', 'description': 'German Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_greece_super_league', 'group': 'Soccer', 'title': 'Super League - Greece', 'description': 'Greek Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_italy_serie_a', 'group': 'Soccer', 'title': 'Serie A - Italy', 'description': 'Italian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_italy_serie_b', 'group': 'Soccer', 'title': 'Serie B - Italy', 'description': 'Italian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_japan_j_league', 'group': 'Soccer', 'title': 'J League', 'description': 'Japan Soccer League', 'active': True, 'has_outrights': False}, {'key': 'soccer_korea_kleague1', 'group': 'Soccer', 'title': 'K League 1', 'description': 'Korean Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_league_of_ireland', 'group': 'Soccer', 'title': 'League of Ireland', 'description': 'Airtricity League Premier Division', 'active': True, 'has_outrights': False}, {'key': 'soccer_mexico_ligamx', 'group': 'Soccer', 'title': 'Liga MX', 'description': 'Mexican Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_netherlands_eredivisie', 'group': 'Soccer', 'title': 'Dutch Eredivisie', 'description': 'Dutch Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_norway_eliteserien', 'group': 'Soccer', 'title': 'Eliteserien - Norway', 'description': 'Norwegian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_poland_ekstraklasa', 'group': 'Soccer', 'title': 'Ekstraklasa - Poland', 'description': 'Polish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_portugal_primeira_liga', 'group': 'Soccer', 'title': 'Primeira Liga - Portugal', 'description': 'Portugese Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_spain_la_liga', 'group': 'Soccer', 'title': 'La Liga - Spain', 'description': 'Spanish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_spain_segunda_division', 'group': 'Soccer', 'title': 'La Liga 2 - Spain', 'description': 'Spanish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_spl', 'group': 'Soccer', 'title': 'Premiership - Scotland', 'description': 'Scottish Premiership', 'active': True, 'has_outrights': False}, {'key': 'soccer_sweden_allsvenskan', 'group': 'Soccer', 'title': 'Allsvenskan - Sweden', 'description': 'Swedish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_sweden_superettan', 'group': 'Soccer', 'title': 'Superettan - Sweden', 'description': 'Swedish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_turkey_super_league', 'group': 'Soccer', 'title': 'Turkey Super League', 'description': 'Turkish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_champs_league', 'group': 'Soccer', 'title': 'UEFA Champions League', 'description': 'European Champions League', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_champs_league_women', 'group': 'Soccer', 'title': 'UEFA Champions League Women', 'description': 'European Champions League Women', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_europa_conference_league', 'group': 'Soccer', 'title': 'UEFA Europa Conference League', 'description': 'UEFA Europa Conference League', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_europa_league', 'group': 'Soccer', 'title': 'UEFA Europa League', 'description': 'European Europa League', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_nations_league', 'group': 'Soccer', 'title': 'UEFA Nations League', 'description': 'UEFA Nations League', 'active': True, 'has_outrights': False}, {'key': 'soccer_usa_mls', 'group': 'Soccer', 'title': 'MLS', 'description': 'Major League Soccer', 'active': True, 'has_outrights': False}, {'key': 'tennis_atp_madrid_open', 'group': 'Tennis', 'title': 'ATP Madrid Open', 'description': "Men's Singles", 'active': True, 'has_outrights': False}, {'key': 'tennis_wta_madrid_open', 'group': 'Tennis', 'title': 'WTA Madrid Open', 'description': "Women's Singles", 'active': True, 'has_outrights': False}]
[
    {
        "key": "americanfootball_ncaaf",
        "group": "American Football",
        "title": "NCAAF",
        "description": "US College Football",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "americanfootball_ncaaf_championship_winner",
        "group": "American Football",
        "title": "NCAAF Championship Winner",
        "description": "US College Football Championship Winner",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "americanfootball_nfl_super_bowl_winner",
        "group": "American Football",
        "title": "NFL Super Bowl Winner",
        "description": "Super Bowl Winner 2025/2026",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "americanfootball_ufl",
        "group": "American Football",
        "title": "UFL",
        "description": "United Football League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "aussierules_afl",
        "group": "Aussie Rules",
        "title": "AFL",
        "description": "Aussie Football",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "baseball_kbo",
        "group": "Baseball",
        "title": "KBO",
        "description": "KBO League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "baseball_milb",
        "group": "Baseball",
        "title": "MiLB",
        "description": "Minor League Baseball",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "baseball_mlb",
        "group": "Baseball",
        "title": "MLB",
        "description": "Major League Baseball",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "baseball_mlb_world_series_winner",
        "group": "Baseball",
        "title": "MLB World Series Winner",
        "description": "World Series Winner 2025",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "baseball_npb",
        "group": "Baseball",
        "title": "NPB",
        "description": "Nippon Professional Baseball",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "basketball_euroleague",
        "group": "Basketball",
        "title": "Basketball Euroleague",
        "description": "Basketball Euroleague",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "basketball_nba",
        "group": "Basketball",
        "title": "NBA",
        "description": "US Basketball",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "basketball_nba_championship_winner",
        "group": "Basketball",
        "title": "NBA Championship Winner",
        "description": "Championship Winner 2024/2025",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "boxing_boxing",
        "group": "Boxing",
        "title": "Boxing",
        "description": "Boxing Bouts",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "cricket_international_t20",
        "group": "Cricket",
        "title": "International Twenty20",
        "description": "International Twenty20",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "cricket_ipl",
        "group": "Cricket",
        "title": "IPL",
        "description": "Indian Premier League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "cricket_psl",
        "group": "Cricket",
        "title": "Pakistan Super League",
        "description": "Pakistan Super League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "cricket_test_match",
        "group": "Cricket",
        "title": "Test Matches",
        "description": "International Test Matches",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "golf_pga_championship_winner",
        "group": "Golf",
        "title": "PGA Championship Winner",
        "description": "2025 Winner",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "golf_the_open_championship_winner",
        "group": "Golf",
        "title": "The Open Winner",
        "description": "2025 Winner",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "golf_us_open_winner",
        "group": "Golf",
        "title": "US Open Winner",
        "description": "2025 Winner",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "icehockey_ahl",
        "group": "Ice Hockey",
        "title": "AHL",
        "description": "American Hockey League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "icehockey_liiga",
        "group": "Ice Hockey",
        "title": "Liiga",
        "description": "Finnish SM League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "icehockey_nhl",
        "group": "Ice Hockey",
        "title": "NHL",
        "description": "US Ice Hockey",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "icehockey_nhl_championship_winner",
        "group": "Ice Hockey",
        "title": "NHL Championship Winner",
        "description": "Stanley Cup Winner 2024/2025",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "icehockey_sweden_allsvenskan",
        "group": "Ice Hockey",
        "title": "HockeyAllsvenskan",
        "description": "Swedish Hockey Allsvenskan",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "icehockey_sweden_hockey_league",
        "group": "Ice Hockey",
        "title": "SHL",
        "description": "Swedish Hockey League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "lacrosse_ncaa",
        "group": "Lacrosse",
        "title": "NCAA Lacrosse",
        "description": "College Lacrosse",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "mma_mixed_martial_arts",
        "group": "Mixed Martial Arts",
        "title": "MMA",
        "description": "Mixed Martial Arts",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "politics_us_presidential_election_winner",
        "group": "Politics",
        "title": "US Presidential Elections Winner",
        "description": "2028 US Presidential Election Winner",
        "active": true,
        "has_outrights": true
    },
    {
        "key": "rugbyleague_nrl",
        "group": "Rugby League",
        "title": "NRL",
        "description": "Aussie Rugby League",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "soccer_argentina_primera_division",
        "group": "Soccer",
        "title": "Primera Divisi\u00f3n - Argentina",
        "description": "Argentine Primera Divisi\u00f3n",
        "active": true,
        "has_outrights": false
    },
    {
        "key": "soccer_australia_aleague",
        "group": "Soccer",
        "title": "A-League",

In [2023]:
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# Now get a list of live & upcoming games for the sport you want, along with odds for different bookmakers
# This will deduct from the usage quota
# The usage quota cost = [number of markets specified] x [number of regions specified]
# For examples of usage quota costs, see https://the-odds-api.com/liveapi/guides/v4/#usage-quota-costs
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
SPORT = 'tennis_atp_madrid_open' # use the sport_key from the /sports endpoint below, or use 'upcoming' to see the next 8 games across all sports
REGIONS = 'us' # uk | us | eu | au. Multiple can be specified if comma delimited
MARKETS = 'h2h' # h2h | spreads | totals. Multiple can be specified if comma delimited
ODDS_FORMAT = 'decimal' # decimal | american
DATE_FORMAT = 'iso' # iso | unix
TimeFrom = '2025-02-10T00:00:00Z'
TimeTo = '2025-05-10T00:00:00Z'
iso_Time_From = datetime.strptime(TimeFrom, "%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%dT%H:%M:%SZ")
iso_Time_To = datetime.strptime(TimeTo, "%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%dT%H:%M:%SZ")


odds_response = requests.get(
    f'https://api.the-odds-api.com/v4/sports/{SPORT}/odds',
    params={
        'api_key': API_KEY,
        'regions': REGIONS,
        'markets': MARKETS,
        'oddsFormat': ODDS_FORMAT,
        'dateFormat': DATE_FORMAT,
        'commenceTimeFrom' : iso_Time_From,
        'commenceTimeTo' : iso_Time_To
    }
)
if odds_response.status_code != 200:
    print(f'Failed to get odds: status_code {odds_response.status_code}, response body {odds_response.text}')


else:
    odds_json = odds_response.json()
    print('Number of events:', len(odds_json))
    print(odds_json)
    games_data = odds_json
    # Save the response to a file
    with open("games_data.json", "w") as file:
        json.dump(games_data, file)

    # Check the usage quota
    print('Remaining requests', odds_response.headers['x-requests-remaining'])
    print('Used requests', odds_response.headers['x-requests-used'])

Number of events: 27

In [2024]:
import pandas as pd
pd.set_option('display.max_columns', None)

with open('games_data.json', 'r') as file:
    data = json.load(file)

#print(data)
pretty_data = json.dumps(data, indent=4)
print(pretty_data)

[
    {
        "id": "a68ad59c9c2951472556a17ed586dc13",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-22T12:48:13Z",
        "home_team": "Borna Gojo",
        "away_team": "Jerome Kym",
        "bookmakers": [
            {
                "key": "fanduel",
                "title": "FanDuel",
                "last_update": "2025-04-22T14:07:31Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:31Z",
                        "outcomes": [
                            {
                                "name": "Borna Gojo",
                                "price": 1.02
                            },
                            {
                                "name": "Jerome Kym",
                                "price": 14.0
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "id": "fa09bda7ee6c41301934208dfa70fedf",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-22T12:52:30Z",
        "home_team": "Gabriel Diallo",
        "away_team": "Borna Coric",
        "bookmakers": [
            {
                "key": "fanduel",
                "title": "FanDuel",
                "last_update": "2025-04-22T14:07:31Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:31Z",
                        "outcomes": [
                            {
                                "name": "Borna Coric",
                                "price": 1.22
                            },
                            {
                                "name": "Gabriel Diallo",
                                "price": 3.8
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "id": "9d007b5ff2343417ef0367234f0960ce",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-22T14:00:00Z",
        "home_team": "Hugo Gaston",
        "away_team": "Luca Nardi",
        "bookmakers": [
            {
                "key": "betonlineag",
                "title": "BetOnline.ag",
                "last_update": "2025-04-22T13:54:25Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T13:54:25Z",
                        "outcomes": [
                            {
                                "name": "Hugo Gaston",
                                "price": 1.7
                            },
                            {
                                "name": "Luca Nardi",
                                "price": 2.22
                            }
                        ]
                    }
                ]
            },
            {
                "key": "lowvig",
                "title": "LowVig.ag",
                "last_update": "2025-04-22T13:54:25Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T13:54:25Z",
                        "outcomes": [
                            {
                                "name": "Hugo Gaston",
                                "price": 1.7
                            },
                            {
                                "name": "Luca Nardi",
                                "price": 2.22
                            }
                        ]
                    }
                ]
            },
            {
                "key": "fanduel",
                "title": "FanDuel",
                "last_update": "2025-04-22T14:07:31Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:31Z",
                        "outcomes": [
                            {
                                "name": "Hugo Gaston",
                                "price": 1.77
                            },
                            {
                                "name": "Luca Nardi",
                                "price": 2.0
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "id": "3688a558859c5d60ea01f53c3be0a06b",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-22T15:00:00Z",
        "home_team": "Daniel Altmaier",
        "away_team": "Daniel Elahi Galan",
        "bookmakers": [
            {
                "key": "betonlineag",
                "title": "BetOnline.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Daniel Altmaier",
                                "price": 1.57
                            },
                            {
                                "name": "Daniel Elahi Galan",
                                "price": 2.55
                            }
                        ]
                    }
                ]
            },
            {
                "key": "lowvig",
                "title": "LowVig.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Daniel Altmaier",
                                "price": 1.57
                            },
                            {
                                "name": "Daniel Elahi Galan",
                                "price": 2.55
                            }
                        ]
                    }
                ]
            },
            {
                "key": "fanduel",
                "title": "FanDuel",
                "last_update": "2025-04-22T14:07:31Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:31Z",
                        "outcomes": [
                            {
                                "name": "Daniel Altmaier",
                                "price": 1.53
                            },
                            {
                                "name": "Daniel Elahi Galan",
                                "price": 2.48
                            }
                        ]
                    }
                ]
            },
            {
                "key": "bovada",
                "title": "Bovada",
                "last_update": "2025-04-22T14:07:34Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:34Z",
                        "outcomes": [
                            {
                                "name": "Daniel Altmaier",
                                "price": 1.57
                            },
                            {
                                "name": "Daniel Elahi Galan",
                                "price": 2.45
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "id": "9b4c8f22e75be5092f0c8483967029ba",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-22T15:00:00Z",
        "home_team": "Kamil Majchrzak",
        "away_team": "Elmer Moller",
        "bookmakers": [
            {
                "key": "fanduel",
                "title": "FanDuel",
                "last_update": "2025-04-22T14:07:31Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:31Z",
                        "outcomes": [
                            {
                                "name": "Elmer Moller",
                                "price": 2.32
                            },
                            {
                                "name": "Kamil Majchrzak",
                                "price": 1.6
                            }
                        ]
                    }
                ]
            },
            {
                "key": "betonlineag",
                "title": "BetOnline.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Elmer Moller",
                                "price": 2.25
                            },
                            {
                                "name": "Kamil Majchrzak",
                                "price": 1.69
                            }
                        ]
                    }
                ]
            },
            {
                "key": "lowvig",
                "title": "LowVig.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Elmer Moller",
                                "price": 2.25
                            },
                            {
                                "name": "Kamil Majchrzak",
                                "price": 1.69
                            }
                        ]
                    }
                ]
            },
            {
                "key": "bovada",
                "title": "Bovada",
                "last_update": "2025-04-22T14:07:34Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:34Z",
                        "outcomes": [
                            {
                                "name": "Elmer Moller",
                                "price": 2.3
                            },
                            {
                                "name": "Kamil Majchrzak",
                                "price": 1.65
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "id": "65fb3f803ffee14d7321ad51da5f77bc",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-22T15:00:00Z",
        "home_team": "Thiago Monteiro",
        "away_team": "Ethan Quinn",
        "bookmakers": [
            {
                "key": "fanduel",
                "title": "FanDuel",
                "last_update": "2025-04-22T14:07:31Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:31Z",
                        "outcomes": [
                            {
                                "name": "Ethan Quinn",
                                "price": 2.26
                            },
                            {
                                "name": "Thiago Monteiro",
                                "price": 1.63
                            }
                        ]
                    }
                ]
            },
            {
                "key": "betonlineag",
                "title": "BetOnline.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Ethan Quinn",
                                "price": 2.37
                            },
                            {
                                "name": "Thiago Monteiro",
                                "price": 1.64
                            }
                        ]
                    }
                ]
            },
            {
                "key": "lowvig",
                "title": "LowVig.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Ethan Quinn",
                                "price": 2.37
                            },
                            {
                                "name": "Thiago Monteiro",
                                "price": 1.64
                            }
                        ]
                    }
                ]
            },
            {
                "key": "bovada",
                "title": "Bovada",
                "last_update": "2025-04-22T14:07:34Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:34Z",
                        "outcomes": [
                            {
                                "name": "Ethan Quinn",
                                "price": 2.35
                            },
                            {
                                "name": "Thiago Monteiro",
                                "price": 1.61
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "id": "03483ea22393072e4fbe34ae03e27fc5",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-22T15:00:00Z",
        "home_team": "Rinky Hijikata",
        "away_team": "Fabio Fognini",
        "bookmakers": [
            {
                "key": "fanduel",
                "title": "FanDuel",
                "last_update": "2025-04-22T14:07:31Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:31Z",
                        "outcomes": [
                            {
                                "name": "Fabio Fognini",
                                "price": 1.53
                            },
                            {
                                "name": "Rinky Hijikata",
                                "price": 2.48
                            }
                        ]
                    }
                ]
            },
            {
                "key": "lowvig",
                "title": "LowVig.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Fabio Fognini",
                                "price": 1.58
                            },
                            {
                                "name": "Rinky Hijikata",
                                "price": 2.52
                            }
                        ]
                    }
                ]
            },
            {
                "key": "betonlineag",
                "title": "BetOnline.ag",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Fabio Fognini",
                                "price": 1.58
                            },
                            {
                                "name": "Rinky Hijikata",
                                "price": 2.52
                            }
                        ]
                    }
                ]
            },
            {
                "key": "bovada",
                "title": "Bovada",
                "last_update": "2025-04-22T14:07:34Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:34Z",
                        "outcomes": [
                            {
                                "name": "Fabio Fognini",
                                "price": 1.51
                            },
                            {
                                "name": "Rinky Hijikata",
                                "price": 2.6
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "id": "51f3ae0ddb5101a214de527ab3ba5f27",
        "sport_key": "tennis_atp_madrid_open",
        "sport_title": "ATP Madrid Open",
        "commence_time": "2025-04-23T08:00:00Z",
        "home_team": "Damir Dzumhur",
        "away_team": "Mattia Bellucci",
        "bookmakers": [
            {
                "key": "bovada",
                "title": "Bovada",
                "last_update": "2025-04-22T14:07:34Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:34Z",
                        "outcomes": [
                            {
                                "name": "Damir Dzumhur",
                                "price": 1.69
                            },
                            {
                                "name": "Mattia Bellucci",
                                "price": 2.2
                            }
                        ]
                    }
                ]
            },
            {
                "key": "draftkings",
                "title": "DraftKings",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Damir Dzumhur",
                                "price": 1.67
                            },
                            {
                                "name": "Mattia Bellucci",
                                "price": 2.1
                            }
                        ]
                    }
                ]
            },
            {
                "key": "betmgm",
                "title": "BetMGM",
                "last_update": "2025-04-22T14:07:30Z",
                "markets": [
                    {
                        "key": "h2h",
                        "last_update": "2025-04-22T14:07:30Z",
                        "outcomes": [
                            {
                                "name": "Damir Dzumhur",
                                "price": 1.67
                            },
                            {

In [2025]:
from datetime import datetime
import pytz

extracted_data = []
utc_zone = pytz.timezone('UTC')
eastern_zone = pytz.timezone('US/Eastern')
# Loop through each entry in the JSON
for entry in data:
    match_id = entry['id']
    home_team = entry['home_team']
    away_team = entry['away_team']
    startDateTime = entry['commence_time']
    utc_time = datetime.strptime(startDateTime, "%Y-%m-%dT%H:%M:%SZ")
    utc_time = utc_zone.localize(utc_time)
    eastern_time = utc_time.astimezone(eastern_zone)
    eastern_time.strftime('%Y-%m-%d %H:%M:%S %Z')

    for bookmaker in entry['bookmakers']:
        bookmaker_title = bookmaker['title']
        
        # Loop through markets and find where market key is 'h2h'
        for market in bookmaker['markets']:
            if market['key'] == 'h2h':
                for outcome in market['outcomes']:
                    extracted_data.append({
                        'ID': match_id,
                        'StartDate': eastern_time,
                        'HomeTeam': home_team,
                        'AwayTeam': away_team,
                        'Bookmaker': bookmaker_title,
                        'OutcomeTeam': outcome['name'],
                        'Price': outcome['price']
                    })

# Create DataFrame
df = pd.DataFrame(extracted_data)

# Display DataFrame
print(df)

                                   ID                 StartDate  \
0    a68ad59c9c2951472556a17ed586dc13 2025-04-22 08:48:13-04:00
1    a68ad59c9c2951472556a17ed586dc13 2025-04-22 08:48:13-04:00
2    fa09bda7ee6c41301934208dfa70fedf 2025-04-22 08:52:30-04:00
3    fa09bda7ee6c41301934208dfa70fedf 2025-04-22 08:52:30-04:00
4    9d007b5ff2343417ef0367234f0960ce 2025-04-22 10:00:00-04:00
..                                ...                       ...
271  611ac12da9bac5dda2d73b53ebe10b8b 2025-04-24 05:00:00-04:00
272  611ac12da9bac5dda2d73b53ebe10b8b 2025-04-24 05:00:00-04:00
273  611ac12da9bac5dda2d73b53ebe10b8b 2025-04-24 05:00:00-04:00
274  611ac12da9bac5dda2d73b53ebe10b8b 2025-04-24 05:00:00-04:00
275  611ac12da9bac5dda2d73b53ebe10b8b 2025-04-24 05:00:00-04:00

           HomeTeam            AwayTeam     Bookmaker         OutcomeTeam  \
0        Borna Gojo          Jerome Kym       FanDuel          Borna Gojo
1        Borna Gojo          Jerome Kym       FanDuel          Jerome Kym
2    Gabriel Diallo         Borna Coric       FanDuel         Borna Coric
3    Gabriel Diallo         Borna Coric       FanDuel      Gabriel Diallo
4       Hugo Gaston          Luca Nardi  BetOnline.ag         Hugo Gaston
..              ...                 ...           ...                 ...
271     Zizou Bergs  Yoshihito Nishioka        Bovada         Zizou Bergs
272     Zizou Bergs  Yoshihito Nishioka  BetOnline.ag  Yoshihito Nishioka
273     Zizou Bergs  Yoshihito Nishioka  BetOnline.ag         Zizou Bergs
274     Zizou Bergs  Yoshihito Nishioka     LowVig.ag  Yoshihito Nishioka
275     Zizou Bergs  Yoshihito Nishioka     LowVig.ag         Zizou Bergs

     Price
0     1.02
1    14.00
2     1.22
3     3.80
4     1.70
..     ...
271   1.22
272   4.60
273   1.22
274   4.60
275   1.22

[276 rows x 7 columns]

In [2026]:
df['adjusted_price'] = ((df['Price'] * 1) - 1)

In [2027]:
def decimal_to_us_odds(decimal_odds):
    if decimal_odds == 1.00:
        return 0  # No payout, return 0 or another meaningful value
    elif decimal_odds >= 2:
        # Underdogs: (decimal_odds - 1) * 100
        return (decimal_odds - 1) * 100
    else:
        # Favorites: -100 / (decimal_odds - 1)
        return -100 / (decimal_odds - 1)

In [2028]:
def extract_date(datetime):
    # Parse the datetime string
    dt = datetime.date()
    time = datetime.time()
    # Extract the date part
    return dt

def extract_time(datetime):
    # Parse the datetime string
    time = datetime.time()
    # Extract the date part
    return time

In [2029]:
df['US_Odds'] = df['Price'].apply(decimal_to_us_odds)
df

,ID,StartDate,HomeTeam,AwayTeam,Bookmaker,OutcomeTeam,Price,adjusted_price,US_Odds
0,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13-04:00,Borna Gojo,Jerome Kym,FanDuel,Borna Gojo,1.02,0.02,-5000.000000
1,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13-04:00,Borna Gojo,Jerome Kym,FanDuel,Jerome Kym,14.00,13.00,1300.000000
2,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30-04:00,Gabriel Diallo,Borna Coric,FanDuel,Borna Coric,1.22,0.22,-454.545455
3,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30-04:00,Gabriel Diallo,Borna Coric,FanDuel,Gabriel Diallo,3.80,2.80,280.000000
4,9d007b5ff2343417ef0367234f0960ce,2025-04-22 10:00:00-04:00,Hugo Gaston,Luca Nardi,BetOnline.ag,Hugo Gaston,1.70,0.70,-142.857143
...,...,...,...,...,...,...,...,...,...
271,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00-04:00,Zizou Bergs,Yoshihito Nishioka,Bovada,Zizou Bergs,1.22,0.22,-454.545455
272,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00-04:00,Zizou Bergs,Yoshihito Nishioka,BetOnline.ag,Yoshihito Nishioka,4.60,3.60,360.000000
273,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00-04:00,Zizou Bergs,Yoshihito Nishioka,BetOnline.ag,Zizou Bergs,1.22,0.22,-454.545455
274,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00-04:00,Zizou Bergs,Yoshihito Nishioka,LowVig.ag,Yoshihito Nishioka,4.60,3.60,360.000000
275,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00-04:00,Zizou Bergs,Yoshihito Nishioka,LowVig.ag,Zizou Bergs,1.22,0.22,-454.545455

In [2030]:
df['event_date'] = df['StartDate'].apply(extract_date)
df['event_start_time'] = df['StartDate'].apply(extract_time)

cols = ['ID', 'StartDate', 'event_date', 'event_start_time', 'HomeTeam', 'AwayTeam', 'Bookmaker', 'OutcomeTeam', 'Price', 'adjusted_price', 'US_Odds']
df = df[cols]
df['StartDate'] = pd.to_datetime(df['StartDate']).dt.tz_localize(None)
df

,ID,StartDate,event_date,event_start_time,HomeTeam,AwayTeam,Bookmaker,OutcomeTeam,Price,adjusted_price,US_Odds
0,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13,2025-04-22,08:48:13,Borna Gojo,Jerome Kym,FanDuel,Borna Gojo,1.02,0.02,-5000.000000
1,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13,2025-04-22,08:48:13,Borna Gojo,Jerome Kym,FanDuel,Jerome Kym,14.00,13.00,1300.000000
2,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30,2025-04-22,08:52:30,Gabriel Diallo,Borna Coric,FanDuel,Borna Coric,1.22,0.22,-454.545455
3,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30,2025-04-22,08:52:30,Gabriel Diallo,Borna Coric,FanDuel,Gabriel Diallo,3.80,2.80,280.000000
4,9d007b5ff2343417ef0367234f0960ce,2025-04-22 10:00:00,2025-04-22,10:00:00,Hugo Gaston,Luca Nardi,BetOnline.ag,Hugo Gaston,1.70,0.70,-142.857143
...,...,...,...,...,...,...,...,...,...,...,...
271,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,Bovada,Zizou Bergs,1.22,0.22,-454.545455
272,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,BetOnline.ag,Yoshihito Nishioka,4.60,3.60,360.000000
273,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,BetOnline.ag,Zizou Bergs,1.22,0.22,-454.545455
274,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,LowVig.ag,Yoshihito Nishioka,4.60,3.60,360.000000
275,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,LowVig.ag,Zizou Bergs,1.22,0.22,-454.545455

In [2031]:
#df.to_excel('extracted_data.xlsx', index=False)

In [ ]:
#Limit the sportsbooks to only my avaliable sportsbooks. 
accepted_sportsbooks = ['FanDuel', 'DraftKings', 'BetMGM', 'Caesars','BetRivers']

accceptedsportsbooksdf = df[df['Bookmaker'].isin(accepted_sportsbooks)]
df

,ID,StartDate,event_date,event_start_time,HomeTeam,AwayTeam,Bookmaker,OutcomeTeam,Price,adjusted_price,US_Odds
0,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13,2025-04-22,08:48:13,Borna Gojo,Jerome Kym,FanDuel,Borna Gojo,1.02,0.02,-5000.000000
1,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13,2025-04-22,08:48:13,Borna Gojo,Jerome Kym,FanDuel,Jerome Kym,14.00,13.00,1300.000000
2,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30,2025-04-22,08:52:30,Gabriel Diallo,Borna Coric,FanDuel,Borna Coric,1.22,0.22,-454.545455
3,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30,2025-04-22,08:52:30,Gabriel Diallo,Borna Coric,FanDuel,Gabriel Diallo,3.80,2.80,280.000000
4,9d007b5ff2343417ef0367234f0960ce,2025-04-22 10:00:00,2025-04-22,10:00:00,Hugo Gaston,Luca Nardi,BetOnline.ag,Hugo Gaston,1.70,0.70,-142.857143
...,...,...,...,...,...,...,...,...,...,...,...
271,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,Bovada,Zizou Bergs,1.22,0.22,-454.545455
272,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,BetOnline.ag,Yoshihito Nishioka,4.60,3.60,360.000000
273,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,BetOnline.ag,Zizou Bergs,1.22,0.22,-454.545455
274,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,LowVig.ag,Yoshihito Nishioka,4.60,3.60,360.000000
275,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,2025-04-24,05:00:00,Zizou Bergs,Yoshihito Nishioka,LowVig.ag,Zizou Bergs,1.22,0.22,-454.545455

In [2033]:
#Create a list of all the teams
unique_outcome_teams = accceptedsportsbooksdf['OutcomeTeam'].unique()
unique_outcome_teams_list = unique_outcome_teams.tolist()

In [2034]:
#For a specified team in the list find the highest US Odds
def find_highest_us_odds_for_team(df, team_name):
    # Filter the dataframe for the specified team
    team_df = accceptedsportsbooksdf[accceptedsportsbooksdf['OutcomeTeam'] == team_name]

    # Find the row with the highest US odds
    if not team_df.empty:
        # Get the row with the max US_Odds
        max_row = team_df.loc[team_df['US_Odds'].idxmax()]
        
        # Extract the highest US odds and the corresponding sportsbook
        game = max_row['ID']
        highest_us_odds = max_row['US_Odds']
        sportsbook = max_row['Bookmaker']
        outcome_team_name = max_row['OutcomeTeam']
        price = max_row['Price']
        date = max_row['StartDate']

        print(outcome_team_name, highest_us_odds, price, sportsbook)
        
        results.append({
        'gameid': game,
        'Team': outcome_team_name,
        'Highest_US_Odds': highest_us_odds,
        'decimalOdds': price,
        'Sportsbook': sportsbook,
        'date': date
            })

        result_df = pd.DataFrame(results)
    
        return result_df
    else:
        return None, None

# Specify the team name
results = []
for team_name in unique_outcome_teams_list:
    maxvaluedf = find_highest_us_odds_for_team(df, team_name)

maxvaluedf

Borna Gojo -4999.999999999995 1.02 FanDuel
Jerome Kym 1300.0 14.0 FanDuel
Borna Coric -454.5454545454546 1.22 FanDuel
Gabriel Diallo 280.0 3.8 FanDuel
Hugo Gaston -129.87012987012986 1.77 FanDuel
Luca Nardi 122.00000000000001 2.22 BetOnline.ag
Daniel Altmaier -175.43859649122805 1.57 BetOnline.ag
Daniel Elahi Galan 154.99999999999997 2.55 BetOnline.ag
Elmer Moller 131.99999999999997 2.32 FanDuel
Kamil Majchrzak -144.92753623188406 1.69 BetOnline.ag
Ethan Quinn 137.0 2.37 BetOnline.ag
Thiago Monteiro -156.25000000000003 1.64 BetOnline.ag
Fabio Fognini -172.41379310344826 1.58 BetOnline.ag
Rinky Hijikata 152.0 2.52 BetOnline.ag
Damir Dzumhur -138.88888888888889 1.72 BetOnline.ag
Mattia Bellucci 118.00000000000001 2.18 BetMGM
Jordan Thompson 131.99999999999997 2.32 BetOnline.ag
Roberto Carballes Baena -151.51515151515153 1.66 BetOnline.ag
Arthur Rinderknech 160.0 2.6 BetOnline.ag
Roman Safiullin -178.57142857142856 1.56 BetOnline.ag
Chak Lam Coleman Wong 160.0 2.6 BetRivers
Federico Coria -178.57142857142856 1.56 BetOnline.ag
Francisco Comesana -109.8901098901099 1.91 DraftKings
Pedro Martinez -105.26315789473685 1.95 BetOnline.ag
Giovanni Mpetshi Perricard 150.0 2.5 BetOnline.ag
Mariano Navone -166.66666666666663 1.6 BetRivers
Jaume Munar -169.4915254237288 1.59 BetOnline.ag
Roberto Bautista Agut 165.0 2.65 BetRivers
Nuno Borges -129.87012987012986 1.77 DraftKings
Pablo Carreno Busta 117.0 2.17 BetRivers
Benjamin Bonzi 238.0 3.38 BetOnline.ag
Marin Cilic -277.7777777777777 1.36 DraftKings
Camilo Ugo Carabelli -161.29032258064512 1.62 BetOnline.ag
Christopher O'Connell 140.0 2.4 BetOnline.ag
Alexander Bublik 106.0 2.06 BetOnline.ag
Alex Michelsen -120.48192771084337 1.83 DraftKings
Fabian Marozsan -133.33333333333334 1.75 BetOnline.ag
Flavio Cobolli 114.99999999999999 2.15 BetMGM
Aleksandar Vukic 210.0 3.1 BetMGM
Kei Nishikori -238.09523809523813 1.42 BetRivers
Alexandre Muller -125.0 1.8 BetOnline.ag
David Goffin 114.00000000000001 2.14 BetRivers
Cameron Norrie -294.1176470588235 1.34 BetMGM
Martin Landaluce 265.0 3.65 DraftKings
Hamad Medjedovic -149.2537313432836 1.67 DraftKings
Tomas Martin Etcheverry 129.0 2.29 BetOnline.ag
Learner Tien 114.99999999999999 2.15 BetOnline.ag
Marcos Giron -135.13513513513513 1.74 BetMGM
Lorenzo Sonego 145.00000000000003 2.45 BetMGM
Miomir Kecmanovic -161.29032258064512 1.62 BetOnline.ag
Luciano Darderi -243.9024390243903 1.41 BetRivers
Quentin Halys 220.00000000000003 3.2 DraftKings
Yoshihito Nishioka 380.0 4.8 DraftKings
Zizou Bergs -454.5454545454546 1.22 BetRivers

,gameid,Team,Highest_US_Odds,decimalOdds,Sportsbook,date
0,a68ad59c9c2951472556a17ed586dc13,Borna Gojo,-5000.000000,1.02,FanDuel,2025-04-22 08:48:13
1,a68ad59c9c2951472556a17ed586dc13,Jerome Kym,1300.000000,14.00,FanDuel,2025-04-22 08:48:13
2,fa09bda7ee6c41301934208dfa70fedf,Borna Coric,-454.545455,1.22,FanDuel,2025-04-22 08:52:30
3,fa09bda7ee6c41301934208dfa70fedf,Gabriel Diallo,280.000000,3.80,FanDuel,2025-04-22 08:52:30
4,9d007b5ff2343417ef0367234f0960ce,Hugo Gaston,-129.870130,1.77,FanDuel,2025-04-22 10:00:00
5,9d007b5ff2343417ef0367234f0960ce,Luca Nardi,122.000000,2.22,BetOnline.ag,2025-04-22 10:00:00
6,3688a558859c5d60ea01f53c3be0a06b,Daniel Altmaier,-175.438596,1.57,BetOnline.ag,2025-04-22 11:00:00
7,3688a558859c5d60ea01f53c3be0a06b,Daniel Elahi Galan,155.000000,2.55,BetOnline.ag,2025-04-22 11:00:00
8,9b4c8f22e75be5092f0c8483967029ba,Elmer Moller,132.000000,2.32,FanDuel,2025-04-22 11:00:00
9,9b4c8f22e75be5092f0c8483967029ba,Kamil Majchrzak,-144.927536,1.69,BetOnline.ag,2025-04-22 11:00:00
10,65fb3f803ffee14d7321ad51da5f77bc,Ethan Quinn,137.000000,2.37,BetOnline.ag,2025-04-22 11:00:00
11,65fb3f803ffee14d7321ad51da5f77bc,Thiago Monteiro,-156.250000,1.64,BetOnline.ag,2025-04-22 11:00:00
12,03483ea22393072e4fbe34ae03e27fc5,Fabio Fognini,-172.413793,1.58,BetOnline.ag,2025-04-22 11:00:00
13,03483ea22393072e4fbe34ae03e27fc5,Rinky Hijikata,152.000000,2.52,BetOnline.ag,2025-04-22 11:00:00
14,51f3ae0ddb5101a214de527ab3ba5f27,Damir Dzumhur,-138.888889,1.72,BetOnline.ag,2025-04-23 04:00:00
15,51f3ae0ddb5101a214de527ab3ba5f27,Mattia Bellucci,118.000000,2.18,BetMGM,2025-04-23 04:00:00
16,c5f6608f1dfc5d368e63935eeb42bb42,Jordan Thompson,132.000000,2.32,BetOnline.ag,2025-04-23 04:00:00
17,c5f6608f1dfc5d368e63935eeb42bb42,Roberto Carballes Baena,-151.515152,1.66,BetOnline.ag,2025-04-23 04:00:00
18,0a6cbb0f20db73fb694597ca817f01c5,Arthur Rinderknech,160.000000,2.60,BetOnline.ag,2025-04-23 05:00:00
19,0a6cbb0f20db73fb694597ca817f01c5,Roman Safiullin,-178.571429,1.56,BetOnline.ag,2025-04-23 05:00:00
20,17699bfd8aec32f3a6b407a6e8475cd0,Chak Lam Coleman Wong,160.000000,2.60,BetRivers,2025-04-23 05:00:00
21,17699bfd8aec32f3a6b407a6e8475cd0,Federico Coria,-178.571429,1.56,BetOnline.ag,2025-04-23 05:00:00
22,1db400b6da31a3be36772d5e308044ba,Francisco Comesana,-109.890110,1.91,DraftKings,2025-04-23 05:00:00
23,1db400b6da31a3be36772d5e308044ba,Pedro Martinez,-105.263158,1.95,BetOnline.ag,2025-04-23 05:00:00
24,9c846608e7b65d8f53b96e66cbb93c9f,Giovanni Mpetshi Perricard,150.000000,2.50,BetOnline.ag,2025-04-23 05:00:00
25,9c846608e7b65d8f53b96e66cbb93c9f,Mariano Navone,-166.666667,1.60,BetRivers,2025-04-23 05:00:00
26,993c6f0bbf39f79bd48382d2dc43a6e7,Jaume Munar,-169.491525,1.59,BetOnline.ag,2025-04-23 05:00:00
27,993c6f0bbf39f79bd48382d2dc43a6e7,Roberto Bautista Agut,165.000000,2.65,BetRivers,2025-04-23 05:00:00
28,3830bc1f5376d1f1b568091b0ab2fe37,Nuno Borges,-129.870130,1.77,DraftKings,2025-04-23 05:00:00
29,3830bc1f5376d1f1b568091b0ab2fe37,Pablo Carreno Busta,117.000000,2.17,BetRivers,2025-04-23 05:00:00
30,3cb75e1e77f35706b43bdf1a49b74ba5,Benjamin Bonzi,238.000000,3.38,BetOnline.ag,2025-04-23 06:10:00
31,3cb75e1e77f35706b43bdf1a49b74ba5,Marin Cilic,-277.777778,1.36,DraftKings,2025-04-23 06:10:00
32,45821e959679bfa01d7a06621f912ca6,Camilo Ugo Carabelli,-161.290323,1.62,BetOnline.ag,2025-04-23 06:10:00
33,45821e959679bfa01d7a06621f912ca6,Christopher O'Connell,140.000000,2.40,BetOnline.ag,2025-04-23 06:10:00
34,6baade83dab9aa7b1142e93632fc2f29,Alexander Bublik,106.000000,2.06,BetOnline.ag,2025-04-23 10:30:00
35,6baade83dab9aa7b1142e93632fc2f29,Alex Michelsen,-120.481928,1.83,DraftKings,2025-04-23 10:30:00
36,4a30242dd14f99799854f6db29d38b79,Fabian Marozsan,-133.333333,1.75,BetOnline.ag,2025-04-23 11:40:00
37,4a30242dd14f99799854f6db29d38b79,Flavio Cobolli,115.000000,2.15,BetMGM,2025-04-23 11:40:00
38,68c9e3568ec8925d6758465bda92a6d6,Aleksandar Vukic,210.000000,3.10,BetMGM,2025-04-24 05:00:00
39,68c9e3568ec8925d6758465bda92a6d6,Kei Nishikori,-238.095238,1.42,BetRivers,2025-04-24 05:00:00
40,8f4baedfce4d5362ba0809e9fc662d3a,Alexandre Muller,-125.000000,1.80,BetOnline.ag,2025-04-24 05:00:00
41,8f4baedfce4d5362ba0809e9fc662d3a,David Goffin,114.000000,2.14,BetRivers,2025-04-24 05:00:00
42,1f40f615b9474925c349ed7ebc5fdba1,Cameron Norrie,-294.117647,1.34,BetMGM,2025-04-24 05:00:00
43,1f40f615b9474925c349ed7ebc5fdba1,Martin Landaluce,265.000000,3.65,DraftKings,2025-04-24 05:00:00
44,dfe5a60d26045b9c2cbac9e27bd1427c,Hamad Medjedovic,-149.253731,1.67,DraftKings,2025-04-24 05:00:00
45,dfe5a60d26045b9c2cbac9e27bd1427c,Tomas Martin Etcheverry,129.000000,2.29,BetOnline.ag,2025-04-24 05:00:00
46,0018260111844dcd271ce28093be80dd,Learner Tien,115.000000,2.15,BetOnline.ag,2025-04-24 05:00:00
47,0018260111844dcd271ce28093be80dd,Marcos Giron,-135.135135,1.74,BetMGM,2025-04-24 05:00:00
48,5d69851258b5528e0fe7f3a397a1463e,Lorenzo Sonego,145.000000,2.45,BetMGM,2025-04-24 05:00:00
49,5d69851258b5528e0fe7f3a397a1463e,Miomir Kecmanovic,-161.290323,1.62,BetOnline.ag,2025-04-24 05:00:00
50,8d5758e62dd410cf2fca1d3af13f6480,Luciano Darderi,-243.902439,1.41,BetRivers,2025-04-24 05:00:00
51,8d5758e62dd410cf2fca1d3af13f6480,Quentin Halys,220.000000,3.20,DraftKings,2025-04-24 05:00:00
52,611ac12da9bac5dda2d73b53ebe10b8b,Yoshihito Nishioka,380.000000,4.80,DraftKings,2025-04-24 05:00:00
53,611ac12da9bac5dda2d73b53ebe10b8b,Zizou Bergs,-454.545455,1.22,BetRivers,2025-04-24 05:00:00

In [2035]:
df_pivot = pd.pivot_table(maxvaluedf, 
                          index=['gameid', 'date'], 
                          columns=maxvaluedf.groupby('gameid').cumcount() + 1, 
                          values=['Team', 'Highest_US_Odds', 'decimalOdds','Sportsbook'], 
                          aggfunc='first')

# Flatten the columns to make them more readable
df_pivot.columns = [f'{col[0]}{col[1]}' for col in df_pivot.columns]

# Reset index for cleaner output
df_pivot = df_pivot.reset_index()

# Display the pivoted dataframe
df_pivot['stake'] = 50
df_pivot

,gameid,date,Highest_US_Odds1,Highest_US_Odds2,Sportsbook1,Sportsbook2,Team1,Team2,decimalOdds1,decimalOdds2,stake
0,0018260111844dcd271ce28093be80dd,2025-04-24 05:00:00,115.000000,-135.135135,BetOnline.ag,BetMGM,Learner Tien,Marcos Giron,2.15,1.74,50
1,03483ea22393072e4fbe34ae03e27fc5,2025-04-22 11:00:00,-172.413793,152.000000,BetOnline.ag,BetOnline.ag,Fabio Fognini,Rinky Hijikata,1.58,2.52,50
2,0a6cbb0f20db73fb694597ca817f01c5,2025-04-23 05:00:00,160.000000,-178.571429,BetOnline.ag,BetOnline.ag,Arthur Rinderknech,Roman Safiullin,2.60,1.56,50
3,17699bfd8aec32f3a6b407a6e8475cd0,2025-04-23 05:00:00,160.000000,-178.571429,BetRivers,BetOnline.ag,Chak Lam Coleman Wong,Federico Coria,2.60,1.56,50
4,1db400b6da31a3be36772d5e308044ba,2025-04-23 05:00:00,-109.890110,-105.263158,DraftKings,BetOnline.ag,Francisco Comesana,Pedro Martinez,1.91,1.95,50
5,1f40f615b9474925c349ed7ebc5fdba1,2025-04-24 05:00:00,-294.117647,265.000000,BetMGM,DraftKings,Cameron Norrie,Martin Landaluce,1.34,3.65,50
6,3688a558859c5d60ea01f53c3be0a06b,2025-04-22 11:00:00,-175.438596,155.000000,BetOnline.ag,BetOnline.ag,Daniel Altmaier,Daniel Elahi Galan,1.57,2.55,50
7,3830bc1f5376d1f1b568091b0ab2fe37,2025-04-23 05:00:00,-129.870130,117.000000,DraftKings,BetRivers,Nuno Borges,Pablo Carreno Busta,1.77,2.17,50
8,3cb75e1e77f35706b43bdf1a49b74ba5,2025-04-23 06:10:00,238.000000,-277.777778,BetOnline.ag,DraftKings,Benjamin Bonzi,Marin Cilic,3.38,1.36,50
9,45821e959679bfa01d7a06621f912ca6,2025-04-23 06:10:00,-161.290323,140.000000,BetOnline.ag,BetOnline.ag,Camilo Ugo Carabelli,Christopher O'Connell,1.62,2.40,50
10,4a30242dd14f99799854f6db29d38b79,2025-04-23 11:40:00,-133.333333,115.000000,BetOnline.ag,BetMGM,Fabian Marozsan,Flavio Cobolli,1.75,2.15,50
11,51f3ae0ddb5101a214de527ab3ba5f27,2025-04-23 04:00:00,-138.888889,118.000000,BetOnline.ag,BetMGM,Damir Dzumhur,Mattia Bellucci,1.72,2.18,50
12,5d69851258b5528e0fe7f3a397a1463e,2025-04-24 05:00:00,145.000000,-161.290323,BetMGM,BetOnline.ag,Lorenzo Sonego,Miomir Kecmanovic,2.45,1.62,50
13,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,380.000000,-454.545455,DraftKings,BetRivers,Yoshihito Nishioka,Zizou Bergs,4.80,1.22,50
14,65fb3f803ffee14d7321ad51da5f77bc,2025-04-22 11:00:00,137.000000,-156.250000,BetOnline.ag,BetOnline.ag,Ethan Quinn,Thiago Monteiro,2.37,1.64,50
15,68c9e3568ec8925d6758465bda92a6d6,2025-04-24 05:00:00,210.000000,-238.095238,BetMGM,BetRivers,Aleksandar Vukic,Kei Nishikori,3.10,1.42,50
16,6baade83dab9aa7b1142e93632fc2f29,2025-04-23 10:30:00,106.000000,-120.481928,BetOnline.ag,DraftKings,Alexander Bublik,Alex Michelsen,2.06,1.83,50
17,8d5758e62dd410cf2fca1d3af13f6480,2025-04-24 05:00:00,-243.902439,220.000000,BetRivers,DraftKings,Luciano Darderi,Quentin Halys,1.41,3.20,50
18,8f4baedfce4d5362ba0809e9fc662d3a,2025-04-24 05:00:00,-125.000000,114.000000,BetOnline.ag,BetRivers,Alexandre Muller,David Goffin,1.80,2.14,50
19,993c6f0bbf39f79bd48382d2dc43a6e7,2025-04-23 05:00:00,-169.491525,165.000000,BetOnline.ag,BetRivers,Jaume Munar,Roberto Bautista Agut,1.59,2.65,50
20,9b4c8f22e75be5092f0c8483967029ba,2025-04-22 11:00:00,132.000000,-144.927536,FanDuel,BetOnline.ag,Elmer Moller,Kamil Majchrzak,2.32,1.69,50
21,9c846608e7b65d8f53b96e66cbb93c9f,2025-04-23 05:00:00,150.000000,-166.666667,BetOnline.ag,BetRivers,Giovanni Mpetshi Perricard,Mariano Navone,2.50,1.60,50
22,9d007b5ff2343417ef0367234f0960ce,2025-04-22 10:00:00,-129.870130,122.000000,FanDuel,BetOnline.ag,Hugo Gaston,Luca Nardi,1.77,2.22,50
23,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13,-5000.000000,1300.000000,FanDuel,FanDuel,Borna Gojo,Jerome Kym,1.02,14.00,50
24,c5f6608f1dfc5d368e63935eeb42bb42,2025-04-23 04:00:00,132.000000,-151.515152,BetOnline.ag,BetOnline.ag,Jordan Thompson,Roberto Carballes Baena,2.32,1.66,50
25,dfe5a60d26045b9c2cbac9e27bd1427c,2025-04-24 05:00:00,-149.253731,129.000000,DraftKings,BetOnline.ag,Hamad Medjedovic,Tomas Martin Etcheverry,1.67,2.29,50
26,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30,-454.545455,280.000000,FanDuel,FanDuel,Borna Coric,Gabriel Diallo,1.22,3.80,50

In [2036]:
#df_pivot.iat[2,8]=2.34

In [2037]:
def implied_probability(decimal_odds):
    if decimal_odds <= 1:  # Handle non-positive odds case
        return None
    return 1 / decimal_odds

def calculate_arbitrage(row):
    prob1 = implied_probability(row['decimalOdds1'])
    prob2 = implied_probability(row['decimalOdds2'])
    
    # Skip if one of the probabilities is None
    if prob1 is None or prob2 is None:
        return pd.Series({
            "Arbitrage_Opportunity": False,
            "Arbitrage_Percentage": None,
            "prob1": None,
            "prob2": None,            
            "Stake_on_Team1": None,
            "Stake_on_Team2": None
        })

    total_prob = prob1 + prob2
    
    if total_prob < 1:
        arbitrage_percentage = 1 - total_prob
        stake1 = (row['stake'] * prob2) / total_prob
        stake2 = (row['stake'] * prob1) / total_prob
        return pd.Series({
            "Arbitrage_Opportunity": True,
            "Arbitrage_Percentage": arbitrage_percentage,
            "prob1": prob1,
            "prob2": prob2,
            "Stake_on_Team1": stake1,
            "Stake_on_Team2": stake2
        })
    else:
        return pd.Series({
            "Arbitrage_Opportunity": False,
            "Arbitrage_Percentage": None,
            "prob1": None,
            "prob2": None,            
            "Stake_on_Team1": None,
            "Stake_on_Team2": None
        })

# Apply the function to each row
arbitrage_results = df_pivot.apply(calculate_arbitrage, axis=1)

# Concatenate results with original DataFrame
result_df = pd.concat([df_pivot, arbitrage_results], axis=1)

# Display the result DataFrame
result_df

,gameid,date,Highest_US_Odds1,Highest_US_Odds2,Sportsbook1,Sportsbook2,Team1,Team2,decimalOdds1,decimalOdds2,stake,Arbitrage_Opportunity,Arbitrage_Percentage,prob1,prob2,Stake_on_Team1,Stake_on_Team2
0,0018260111844dcd271ce28093be80dd,2025-04-24 05:00:00,115.000000,-135.135135,BetOnline.ag,BetMGM,Learner Tien,Marcos Giron,2.15,1.74,50,False,None,None,None,None,None
1,03483ea22393072e4fbe34ae03e27fc5,2025-04-22 11:00:00,-172.413793,152.000000,BetOnline.ag,BetOnline.ag,Fabio Fognini,Rinky Hijikata,1.58,2.52,50,False,None,None,None,None,None
2,0a6cbb0f20db73fb694597ca817f01c5,2025-04-23 05:00:00,160.000000,-178.571429,BetOnline.ag,BetOnline.ag,Arthur Rinderknech,Roman Safiullin,2.60,1.56,50,False,None,None,None,None,None
3,17699bfd8aec32f3a6b407a6e8475cd0,2025-04-23 05:00:00,160.000000,-178.571429,BetRivers,BetOnline.ag,Chak Lam Coleman Wong,Federico Coria,2.60,1.56,50,False,None,None,None,None,None
4,1db400b6da31a3be36772d5e308044ba,2025-04-23 05:00:00,-109.890110,-105.263158,DraftKings,BetOnline.ag,Francisco Comesana,Pedro Martinez,1.91,1.95,50,False,None,None,None,None,None
5,1f40f615b9474925c349ed7ebc5fdba1,2025-04-24 05:00:00,-294.117647,265.000000,BetMGM,DraftKings,Cameron Norrie,Martin Landaluce,1.34,3.65,50,False,None,None,None,None,None
6,3688a558859c5d60ea01f53c3be0a06b,2025-04-22 11:00:00,-175.438596,155.000000,BetOnline.ag,BetOnline.ag,Daniel Altmaier,Daniel Elahi Galan,1.57,2.55,50,False,None,None,None,None,None
7,3830bc1f5376d1f1b568091b0ab2fe37,2025-04-23 05:00:00,-129.870130,117.000000,DraftKings,BetRivers,Nuno Borges,Pablo Carreno Busta,1.77,2.17,50,False,None,None,None,None,None
8,3cb75e1e77f35706b43bdf1a49b74ba5,2025-04-23 06:10:00,238.000000,-277.777778,BetOnline.ag,DraftKings,Benjamin Bonzi,Marin Cilic,3.38,1.36,50,False,None,None,None,None,None
9,45821e959679bfa01d7a06621f912ca6,2025-04-23 06:10:00,-161.290323,140.000000,BetOnline.ag,BetOnline.ag,Camilo Ugo Carabelli,Christopher O'Connell,1.62,2.40,50,False,None,None,None,None,None
10,4a30242dd14f99799854f6db29d38b79,2025-04-23 11:40:00,-133.333333,115.000000,BetOnline.ag,BetMGM,Fabian Marozsan,Flavio Cobolli,1.75,2.15,50,False,None,None,None,None,None
11,51f3ae0ddb5101a214de527ab3ba5f27,2025-04-23 04:00:00,-138.888889,118.000000,BetOnline.ag,BetMGM,Damir Dzumhur,Mattia Bellucci,1.72,2.18,50,False,None,None,None,None,None
12,5d69851258b5528e0fe7f3a397a1463e,2025-04-24 05:00:00,145.000000,-161.290323,BetMGM,BetOnline.ag,Lorenzo Sonego,Miomir Kecmanovic,2.45,1.62,50,False,None,None,None,None,None
13,611ac12da9bac5dda2d73b53ebe10b8b,2025-04-24 05:00:00,380.000000,-454.545455,DraftKings,BetRivers,Yoshihito Nishioka,Zizou Bergs,4.80,1.22,50,False,None,None,None,None,None
14,65fb3f803ffee14d7321ad51da5f77bc,2025-04-22 11:00:00,137.000000,-156.250000,BetOnline.ag,BetOnline.ag,Ethan Quinn,Thiago Monteiro,2.37,1.64,50,False,None,None,None,None,None
15,68c9e3568ec8925d6758465bda92a6d6,2025-04-24 05:00:00,210.000000,-238.095238,BetMGM,BetRivers,Aleksandar Vukic,Kei Nishikori,3.10,1.42,50,False,None,None,None,None,None
16,6baade83dab9aa7b1142e93632fc2f29,2025-04-23 10:30:00,106.000000,-120.481928,BetOnline.ag,DraftKings,Alexander Bublik,Alex Michelsen,2.06,1.83,50,False,None,None,None,None,None
17,8d5758e62dd410cf2fca1d3af13f6480,2025-04-24 05:00:00,-243.902439,220.000000,BetRivers,DraftKings,Luciano Darderi,Quentin Halys,1.41,3.20,50,False,None,None,None,None,None
18,8f4baedfce4d5362ba0809e9fc662d3a,2025-04-24 05:00:00,-125.000000,114.000000,BetOnline.ag,BetRivers,Alexandre Muller,David Goffin,1.80,2.14,50,False,None,None,None,None,None
19,993c6f0bbf39f79bd48382d2dc43a6e7,2025-04-23 05:00:00,-169.491525,165.000000,BetOnline.ag,BetRivers,Jaume Munar,Roberto Bautista Agut,1.59,2.65,50,False,None,None,None,None,None
20,9b4c8f22e75be5092f0c8483967029ba,2025-04-22 11:00:00,132.000000,-144.927536,FanDuel,BetOnline.ag,Elmer Moller,Kamil Majchrzak,2.32,1.69,50,False,None,None,None,None,None
21,9c846608e7b65d8f53b96e66cbb93c9f,2025-04-23 05:00:00,150.000000,-166.666667,BetOnline.ag,BetRivers,Giovanni Mpetshi Perricard,Mariano Navone,2.50,1.60,50,False,None,None,None,None,None
22,9d007b5ff2343417ef0367234f0960ce,2025-04-22 10:00:00,-129.870130,122.000000,FanDuel,BetOnline.ag,Hugo Gaston,Luca Nardi,1.77,2.22,50,False,None,None,None,None,None
23,a68ad59c9c2951472556a17ed586dc13,2025-04-22 08:48:13,-5000.000000,1300.000000,FanDuel,FanDuel,Borna Gojo,Jerome Kym,1.02,14.00,50,False,None,None,None,None,None
24,c5f6608f1dfc5d368e63935eeb42bb42,2025-04-23 04:00:00,132.000000,-151.515152,BetOnline.ag,BetOnline.ag,Jordan Thompson,Roberto Carballes Baena,2.32,1.66,50,False,None,None,None,None,None
25,dfe5a60d26045b9c2cbac9e27bd1427c,2025-04-24 05:00:00,-149.253731,129.000000,DraftKings,BetOnline.ag,Hamad Medjedovic,Tomas Martin Etcheverry,1.67,2.29,50,False,None,None,None,None,None
26,fa09bda7ee6c41301934208dfa70fedf,2025-04-22 08:52:30,-454.545455,280.000000,FanDuel,FanDuel,Borna Coric,Gabriel Diallo,1.22,3.80,50,False,None,None,None,None,None

In [2038]:
#df.to_excel('extracted_data.xlsx', index=False)

In [2039]:
result_df.to_excel('results_data.xlsx', index=False)